window.ADRENAL_SPRINT_BANK = {
  "schemaVersion": "1.0.0",
  "bankId": "adrenal_sprint_v2_3",
  "bankType": "sprint",
  "mode": "learn",
  "sourceLecture": "Adrenal Glands and Adrenal Hormones",
  "questionCount": 40,
  "questions": [
    {
      "id": "ADRN_SPRINT_001",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Gland Anatomy and Medulla",
      "question": "Where are the adrenal glands located?",
      "choices": {
        "A": "Within the posterior pituitary",
        "B": "On the superior poles of the kidneys",
        "C": "Along the inferior border of the thyroid",
        "D": "Inside the pancreatic islets"
      },
      "correctAnswer": "B",
      "explanation": "Each adrenal gland sits above a kidney and contains an outer cortex surrounding a central medulla.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Each adrenal gland sits above a kidney and contains an outer cortex surrounding a central medulla.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 1,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Gland Anatomy and Medulla",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_002",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Gland Anatomy and Medulla",
      "question": "Why is the adrenal medulla considered functionally related to the sympathetic nervous system?",
      "choices": {
        "A": "It produces steroid hormones from cholesterol.",
        "B": "It releases mineralocorticoids during sodium loss.",
        "C": "It responds mainly to anterior pituitary hormones.",
        "D": "Its chromaffin cells release catecholamines during sympathetic activation."
      },
      "correctAnswer": "D",
      "explanation": "Chromaffin cells act as sympathetic neuroendocrine cells, releasing epinephrine and norepinephrine into blood.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chromaffin cells act as sympathetic neuroendocrine cells, releasing epinephrine and norepinephrine into blood.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 2,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Gland Anatomy and Medulla",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_003",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Adrenal Cortex Zones",
      "question": "Which adrenal cortex zone primarily produces glucocorticoids?",
      "choices": {
        "A": "Zona fasciculata",
        "B": "Zona glomerulosa",
        "C": "Zona reticularis",
        "D": "Adrenal medulla"
      },
      "correctAnswer": "A",
      "explanation": "The zona fasciculata is the middle and widest cortical layer and produces cortisol and other glucocorticoids.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The zona fasciculata is the middle and widest cortical layer and produces cortisol and other glucocorticoids.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 3,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Adrenal Cortex Zones",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_004",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Adrenal Cortex Zones",
      "question": "Which function is most closely associated with hormones from the zona reticularis?",
      "choices": {
        "A": "Retaining sodium during volume depletion",
        "B": "Increasing glucose during prolonged stress",
        "C": "Contributing to secondary sex characteristics",
        "D": "Releasing catecholamines during sympathetic activation"
      },
      "correctAnswer": "C",
      "explanation": "The zona reticularis produces adrenal androgens that contribute to secondary sex characteristics.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The zona reticularis produces adrenal androgens that contribute to secondary sex characteristics.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 4,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Adrenal Cortex Zones",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_005",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Steroid Synthesis and Transport",
      "question": "What is the common starting material for adrenal cortex steroid hormones?",
      "choices": {
        "A": "Tyrosine",
        "B": "Cholesterol",
        "C": "Tryptophan",
        "D": "Glycogen"
      },
      "correctAnswer": "B",
      "explanation": "Mineralocorticoids, glucocorticoids, and adrenal androgens are all synthesized from cholesterol.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Mineralocorticoids, glucocorticoids, and adrenal androgens are all synthesized from cholesterol.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 5,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Steroid Synthesis and Transport",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_006",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Steroid Synthesis and Transport",
      "question": "ACTH increases LDL receptors on adrenal cortical cells. What does this support?",
      "choices": {
        "A": "Delivery of cholesterol for steroid synthesis",
        "B": "Storage of catecholamines in chromaffin cells",
        "C": "Conversion of cortisol into aldosterone",
        "D": "Release of renin from the adrenal cortex"
      },
      "correctAnswer": "A",
      "explanation": "Most adrenal cholesterol is supplied by plasma LDL, so increased LDL receptors support substrate delivery for steroid production.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Most adrenal cholesterol is supplied by plasma LDL, so increased LDL receptors support substrate delivery for steroid production.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 6,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Steroid Synthesis and Transport",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_007",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Organization",
      "subtopic": "Steroid Synthesis and Transport",
      "question": "Which statement correctly compares cortisol and aldosterone transport?",
      "choices": {
        "A": "Aldosterone is more protein-bound and has a longer half-life.",
        "B": "Both circulate entirely free and have equal half-lives.",
        "C": "Cortisol circulates entirely free while aldosterone binds transcortin.",
        "D": "Cortisol is more protein-bound and has a longer half-life."
      },
      "correctAnswer": "D",
      "explanation": "Cortisol is 90–95% protein-bound with a 60–90 minute half-life; aldosterone is about 60% bound with a roughly 20 minute half-life.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol is 90–95% protein-bound with a 60–90 minute half-life; aldosterone is about 60% bound with a roughly 20 minute half-life.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 7,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Organization",
        "concept_group": "Steroid Synthesis and Transport",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_008",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Zona Glomerulosa and Regulation",
      "question": "Which feature allows the zona glomerulosa to complete aldosterone synthesis?",
      "choices": {
        "A": "Cortisol-binding globulin",
        "B": "Pro-opiomelanocortin",
        "C": "Aldosterone synthase",
        "D": "Catechol-O-methyltransferase"
      },
      "correctAnswer": "C",
      "explanation": "The zona glomerulosa is the only cortical layer containing aldosterone synthase, which catalyzes the final steps of aldosterone formation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The zona glomerulosa is the only cortical layer containing aldosterone synthase, which catalyzes the final steps of aldosterone formation.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 8,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Zona Glomerulosa and Regulation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_009",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Zona Glomerulosa and Regulation",
      "question": "Which pair provides the strongest stimulation of aldosterone secretion?",
      "choices": {
        "A": "Increased extracellular potassium and angiotensin II",
        "B": "Increased extracellular sodium and ANP",
        "C": "Decreased potassium and increased ANP",
        "D": "Increased cortisol and decreased angiotensin II"
      },
      "correctAnswer": "A",
      "explanation": "Elevated extracellular potassium and angiotensin II are the major stimulators; ACTH has only a minor role in controlling aldosterone secretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Elevated extracellular potassium and angiotensin II are the major stimulators; ACTH has only a minor role in controlling aldosterone secretion.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 9,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Zona Glomerulosa and Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_010",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Renal and Electrolyte Effects",
      "question": "What is aldosterone's primary renal effect?",
      "choices": {
        "A": "Decreased sodium reabsorption and decreased potassium secretion",
        "B": "Increased sodium reabsorption and increased potassium secretion",
        "C": "Increased glucose reabsorption and decreased sodium secretion",
        "D": "Decreased water reabsorption and increased calcium secretion"
      },
      "correctAnswer": "B",
      "explanation": "Aldosterone conserves sodium while promoting potassium secretion in the distal nephron.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Aldosterone conserves sodium while promoting potassium secretion in the distal nephron.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 10,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Renal and Electrolyte Effects",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_011",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Renal and Electrolyte Effects",
      "question": "What combination is expected after severe loss of mineralocorticoid activity?",
      "choices": {
        "A": "Hypernatremia, hypokalemia, and hypertension",
        "B": "Hypernatremia, hyperkalemia, and increased cardiac output",
        "C": "Hyponatremia, hypokalemia, and increased blood volume",
        "D": "Hyponatremia, hyperkalemia, and reduced blood volume"
      },
      "correctAnswer": "D",
      "explanation": "Without aldosterone, sodium and chloride are lost while potassium accumulates, reducing extracellular volume, cardiac output, and blood pressure.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Without aldosterone, sodium and chloride are lost while potassium accumulates, reducing extracellular volume, cardiac output, and blood pressure.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 11,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Renal and Electrolyte Effects",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "ADRN_SPRINT_012",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Renal and Electrolyte Effects",
      "question": "An increase in extracellular potassium has what effect on aldosterone secretion?",
      "choices": {
        "A": "It strongly suppresses secretion.",
        "B": "It has no meaningful effect.",
        "C": "It strongly increases secretion.",
        "D": "It increases secretion only after ACTH falls."
      },
      "correctAnswer": "C",
      "explanation": "Elevated extracellular potassium directly stimulates aldosterone secretion, which promotes renal potassium excretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Elevated extracellular potassium directly stimulates aldosterone secretion, which promotes renal potassium excretion.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 12,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Renal and Electrolyte Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_013",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Zona Glomerulosa and Regulation",
      "question": "How does angiotensin II support blood-volume regulation?",
      "choices": {
        "A": "It stimulates aldosterone, increasing renal sodium retention.",
        "B": "It stimulates ANP, increasing renal sodium loss.",
        "C": "It suppresses aldosterone, increasing potassium retention.",
        "D": "It suppresses renin, increasing water loss."
      },
      "correctAnswer": "A",
      "explanation": "Angiotensin II is a major aldosterone stimulus; the resulting sodium retention supports extracellular volume and blood pressure.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Angiotensin II is a major aldosterone stimulus; the resulting sodium retention supports extracellular volume and blood pressure.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 13,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Zona Glomerulosa and Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_014",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Renal and Electrolyte Effects",
      "question": "What is the effect of increased atrial natriuretic peptide on aldosterone?",
      "choices": {
        "A": "It strongly stimulates aldosterone release.",
        "B": "It converts aldosterone into cortisol.",
        "C": "It extends aldosterone's plasma half-life.",
        "D": "It decreases aldosterone secretion."
      },
      "correctAnswer": "D",
      "explanation": "ANP opposes volume expansion by decreasing aldosterone and favoring sodium excretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "ANP opposes volume expansion by decreasing aldosterone and favoring sodium excretion.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 14,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Renal and Electrolyte Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_015",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Aldosterone Escape and Extra-Renal Effects",
      "question": "Why does renal sodium output eventually return toward normal despite persistent excess aldosterone?",
      "choices": {
        "A": "The zona glomerulosa stops producing all steroids.",
        "B": "Pressure natriuresis and ANP counter continued sodium retention.",
        "C": "Cortisol permanently blocks sodium reabsorption.",
        "D": "Potassium directly prevents renal filtration."
      },
      "correctAnswer": "B",
      "explanation": "Volume and pressure rise until pressure diuresis, pressure natriuresis, suppressed angiotensin II, and increased ANP produce “aldosterone escape.”",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Volume and pressure rise until pressure diuresis, pressure natriuresis, suppressed angiotensin II, and increased ANP produce “aldosterone escape.”",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 15,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Aldosterone Escape and Extra-Renal Effects",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "ADRN_SPRINT_016",
      "unit": "adrenal",
      "conceptBlock": "Aldosterone Physiology",
      "subtopic": "Aldosterone Escape and Extra-Renal Effects",
      "question": "How does aldosterone help conserve salt outside the kidneys?",
      "choices": {
        "A": "It decreases sodium reabsorption in the colon and sweat glands.",
        "B": "It stimulates catecholamine release from salivary glands.",
        "C": "It increases sodium reabsorption in the colon, sweat glands, and salivary glands.",
        "D": "It blocks potassium excretion in the colon and sweat glands."
      },
      "correctAnswer": "C",
      "explanation": "Extra-renal aldosterone action conserves sodium in feces, sweat, and saliva, which is especially useful in hot environments.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Extra-renal aldosterone action conserves sodium in feces, sweat, and saliva, which is especially useful in hot environments.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 16,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Aldosterone Physiology",
        "concept_group": "Aldosterone Escape and Extra-Renal Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_017",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Zona Fasciculata and HPA Regulation",
      "question": "Which hormone is the major glucocorticoid produced by the adrenal cortex?",
      "choices": {
        "A": "Cortisol",
        "B": "Aldosterone",
        "C": "Epinephrine",
        "D": "Dehydroepiandrosterone"
      },
      "correctAnswer": "A",
      "explanation": "Cortisol is the dominant glucocorticoid and is produced mainly by the zona fasciculata.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol is the dominant glucocorticoid and is produced mainly by the zona fasciculata.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 17,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Zona Fasciculata and HPA Regulation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_018",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Zona Fasciculata and HPA Regulation",
      "question": "Which sequence correctly describes the hypothalamic-pituitary-adrenal axis?",
      "choices": {
        "A": "ACTH → CRH → cortisol",
        "B": "CRH → ACTH → cortisol",
        "C": "Cortisol → ACTH → CRH",
        "D": "CRH → cortisol → ACTH"
      },
      "correctAnswer": "B",
      "explanation": "Hypothalamic CRH stimulates anterior pituitary ACTH, which then stimulates cortisol secretion from the adrenal cortex.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Hypothalamic CRH stimulates anterior pituitary ACTH, which then stimulates cortisol secretion from the adrenal cortex.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 18,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Zona Fasciculata and HPA Regulation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_019",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Zona Fasciculata and HPA Regulation",
      "question": "When are CRH, ACTH, and cortisol secretory rates normally highest?",
      "choices": {
        "A": "Immediately after the evening meal",
        "B": "Near midnight",
        "C": "During the first hour of sleep",
        "D": "About one hour before waking"
      },
      "correctAnswer": "D",
      "explanation": "The HPA axis follows a circadian rhythm, peaking shortly before waking and reaching its lowest activity near midnight.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The HPA axis follows a circadian rhythm, peaking shortly before waking and reaching its lowest activity near midnight.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 19,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Zona Fasciculata and HPA Regulation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_020",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Zona Fasciculata and HPA Regulation",
      "question": "Following major physical stress, which hormonal change is expected?",
      "choices": {
        "A": "ACTH falls, followed by lower cortisol.",
        "B": "Aldosterone falls, followed by lower cortisol.",
        "C": "ACTH rises, followed within minutes by higher cortisol.",
        "D": "ANP rises, followed by higher cortisol."
      },
      "correctAnswer": "C",
      "explanation": "Trauma, infection, surgery, temperature extremes, and other stresses increase ACTH and then cortisol.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Trauma, infection, surgery, temperature extremes, and other stresses increase ACTH and then cortisol.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 20,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Zona Fasciculata and HPA Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_021",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Metabolic Effects",
      "question": "How does cortisol help elevate blood glucose?",
      "choices": {
        "A": "It increases cellular GLUT4 translocation in muscle and fat.",
        "B": "It promotes gluconeogenesis and decreases peripheral glucose use.",
        "C": "It blocks amino-acid delivery to the liver.",
        "D": "It prevents fatty-acid mobilization from adipose tissue."
      },
      "correctAnswer": "B",
      "explanation": "Cortisol increases hepatic glucose production while antagonizing insulin-dependent glucose utilization, producing a glucose-sparing effect.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol increases hepatic glucose production while antagonizing insulin-dependent glucose utilization, producing a glucose-sparing effect.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 21,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_022",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Metabolic Effects",
      "question": "What is a major effect of cortisol on protein metabolism outside the liver?",
      "choices": {
        "A": "Reduced protein synthesis and increased protein catabolism",
        "B": "Increased protein storage and reduced amino-acid release",
        "C": "Increased insulin sensitivity and increased protein storage",
        "D": "Reduced amino-acid availability for hepatic gluconeogenesis"
      },
      "correctAnswer": "A",
      "explanation": "Cortisol reduces protein stores in many tissues, releasing amino acids that can be used by the liver.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol reduces protein stores in many tissues, releasing amino acids that can be used by the liver.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 22,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_023",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Metabolic Effects",
      "question": "Which change reflects cortisol's effect on fat metabolism?",
      "choices": {
        "A": "Reduced fatty-acid release from adipose tissue",
        "B": "Complete inhibition of fatty-acid oxidation",
        "C": "Uniform loss of fat from every body region",
        "D": "Mobilization of fatty acids with possible fat redistribution"
      },
      "correctAnswer": "D",
      "explanation": "Cortisol mobilizes adipose fat for energy and, when excessive, contributes to characteristic redistribution toward the chest and head.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol mobilizes adipose fat for energy and, when excessive, contributes to characteristic redistribution toward the chest and head.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 23,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_024",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Stress and Systemic Effects",
      "question": "Why can glucocorticoids reduce inflammation?",
      "choices": {
        "A": "They increase lymphocyte and eosinophil activity.",
        "B": "They increase histamine release from immune cells.",
        "C": "They block or reverse parts of the inflammatory response.",
        "D": "They stimulate antibody production in every tissue."
      },
      "correctAnswer": "C",
      "explanation": "Cortisol has anti-inflammatory and immunosuppressive effects, including decreased eosinophils and lymphocytes.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol has anti-inflammatory and immunosuppressive effects, including decreased eosinophils and lymphocytes.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 24,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Stress and Systemic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_025",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Stress and Systemic Effects",
      "question": "Which additional effect is associated with cortisol?",
      "choices": {
        "A": "Increased responsiveness to catecholamines",
        "B": "Increased bone formation",
        "C": "Decreased red blood cell production",
        "D": "Increased lymphocyte production"
      },
      "correctAnswer": "A",
      "explanation": "Cortisol increases catecholamine responsiveness while reducing bone formation and suppressing parts of the immune system.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol increases catecholamine responsiveness while reducing bone formation and suppressing parts of the immune system.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 25,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Stress and Systemic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_026",
      "unit": "adrenal",
      "conceptBlock": "Cortisol Physiology",
      "subtopic": "Stress and Systemic Effects",
      "question": "Why can excess ACTH be associated with increased pigmentation?",
      "choices": {
        "A": "ACTH is converted directly into melanin in the adrenal cortex.",
        "B": "ACTH and melanocyte-stimulating hormone share the POMC precursor.",
        "C": "ACTH stimulates aldosterone synthase in melanocytes.",
        "D": "ACTH blocks catecholamine release from skin nerves."
      },
      "correctAnswer": "B",
      "explanation": "POMC gives rise to ACTH and melanocyte-stimulating peptides, linking high ACTH activity with pigmentation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "POMC gives rise to ACTH and melanocyte-stimulating peptides, linking high ACTH activity with pigmentation.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 26,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Cortisol Physiology",
        "concept_group": "Stress and Systemic Effects",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_027",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Insufficiency",
      "subtopic": "Primary and Secondary Insufficiency",
      "question": "Which finding best distinguishes primary adrenal insufficiency from pituitary-related secondary insufficiency?",
      "choices": {
        "A": "Primary disease begins with inadequate ACTH from the pituitary.",
        "B": "Primary disease is caused only by abrupt steroid withdrawal.",
        "C": "Primary disease begins with damage or atrophy of the adrenal cortex.",
        "D": "Primary disease initially leaves all adrenal cortex hormones normal."
      },
      "correctAnswer": "C",
      "explanation": "Addison disease is primary cortical failure, whereas impaired pituitary function or abrupt steroid withdrawal can produce secondary insufficiency.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Addison disease is primary cortical failure, whereas impaired pituitary function or abrupt steroid withdrawal can produce secondary insufficiency.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 27,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Insufficiency",
        "concept_group": "Primary and Secondary Insufficiency",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_028",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Insufficiency",
      "subtopic": "Addison Disease and Adrenal Crisis",
      "question": "Which pattern is most consistent with aldosterone deficiency in Addison disease?",
      "choices": {
        "A": "Hypernatremia, hypokalemia, and hypertension",
        "B": "Hypernatremia, metabolic alkalosis, and bradycardia",
        "C": "Hyponatremia, hypokalemia, and increased blood volume",
        "D": "Hyponatremia, hyperkalemia, and hypotension"
      },
      "correctAnswer": "D",
      "explanation": "Aldosterone loss causes salt and volume depletion, potassium retention, reduced cardiac output, and low blood pressure.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Aldosterone loss causes salt and volume depletion, potassium retention, reduced cardiac output, and low blood pressure.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 28,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Insufficiency",
        "concept_group": "Addison Disease and Adrenal Crisis",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_029",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Insufficiency",
      "subtopic": "Addison Disease and Adrenal Crisis",
      "question": "Which symptom is most directly related to cortisol deficiency?",
      "choices": {
        "A": "Hypoglycemia and poor tolerance of stress",
        "B": "Hyperglycemia and increased metabolism",
        "C": "Hypernatremia and increased blood volume",
        "D": "Hypokalemia and metabolic alkalosis"
      },
      "correctAnswer": "A",
      "explanation": "Low cortisol reduces metabolic support for blood glucose and makes the patient more vulnerable to physiologic stress.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low cortisol reduces metabolic support for blood glucose and makes the patient more vulnerable to physiologic stress.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 29,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Insufficiency",
        "concept_group": "Addison Disease and Adrenal Crisis",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_030",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Insufficiency",
      "subtopic": "Addison Disease and Adrenal Crisis",
      "question": "Which presentation should raise concern for an adrenal crisis?",
      "choices": {
        "A": "Hypertension with isolated hyperglycemia",
        "B": "Dehydration, hypotension, hypoglycemia, and vomiting",
        "C": "Increased blood volume with mild alkalosis",
        "D": "Moon face with slowly developing central obesity"
      },
      "correctAnswer": "B",
      "explanation": "Adrenal crisis is a high-mortality endocrine emergency marked by severe volume loss, low pressure, low glucose, gastrointestinal symptoms, and possible loss of consciousness.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Adrenal crisis is a high-mortality endocrine emergency marked by severe volume loss, low pressure, low glucose, gastrointestinal symptoms, and possible loss of consciousness.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 30,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Insufficiency",
        "concept_group": "Addison Disease and Adrenal Crisis",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_031",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Insufficiency",
      "subtopic": "Primary and Secondary Insufficiency",
      "question": "Why can abruptly stopping long-term glucocorticoid medication cause secondary adrenal insufficiency?",
      "choices": {
        "A": "It immediately destroys the zona glomerulosa.",
        "B": "It causes permanent catecholamine depletion.",
        "C": "Prior HPA suppression leaves inadequate ACTH and an atrophied cortex.",
        "D": "Prior treatment permanently increases aldosterone synthase."
      },
      "correctAnswer": "C",
      "explanation": "Exogenous glucocorticoids suppress the HPA axis; abrupt withdrawal can leave insufficient ACTH stimulation before the axis recovers.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Exogenous glucocorticoids suppress the HPA axis; abrupt withdrawal can leave insufficient ACTH stimulation before the axis recovers.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 31,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Insufficiency",
        "concept_group": "Primary and Secondary Insufficiency",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_032",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Cushing Syndrome and Disease",
      "question": "A pituitary ACTH-secreting tumor causes cortisol excess. How should this be classified?",
      "choices": {
        "A": "Primary aldosteronism",
        "B": "Primary adrenal insufficiency",
        "C": "Adrenogenital syndrome",
        "D": "Cushing disease"
      },
      "correctAnswer": "D",
      "explanation": "Cushing disease specifically refers to pituitary ACTH excess; Cushing syndrome describes the broader state of glucocorticoid excess.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cushing disease specifically refers to pituitary ACTH excess; Cushing syndrome describes the broader state of glucocorticoid excess.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 32,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Cushing Syndrome and Disease",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "ADRN_SPRINT_033",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Cushing Syndrome and Disease",
      "question": "What is the most common lecture-listed cause of iatrogenic Cushing syndrome?",
      "choices": {
        "A": "Autoimmune destruction of the adrenal cortex",
        "B": "Administration of glucocorticoid medication",
        "C": "A zona glomerulosa tumor",
        "D": "A catecholamine-secreting medullary tumor"
      },
      "correctAnswer": "B",
      "explanation": "Prolonged therapeutic steroid administration is the common iatrogenic cause of glucocorticoid excess.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Prolonged therapeutic steroid administration is the common iatrogenic cause of glucocorticoid excess.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 33,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Cushing Syndrome and Disease",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_034",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Cushing Syndrome and Disease",
      "question": "Which group of findings most strongly suggests Cushing syndrome?",
      "choices": {
        "A": "Central fat redistribution, hyperglycemia, striae, and poor wound healing",
        "B": "Weight loss, hypoglycemia, salt craving, and hyperkalemia",
        "C": "Episodic headache, sweating, and isolated catecholamine excess",
        "D": "Hyponatremia, dehydration, and increased stress sensitivity"
      },
      "correctAnswer": "A",
      "explanation": "Chronic glucocorticoid excess produces fat redistribution, impaired tissue repair, hyperglycemia, weakness, hypertension, osteoporosis, and infection susceptibility.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chronic glucocorticoid excess produces fat redistribution, impaired tissue repair, hyperglycemia, weakness, hypertension, osteoporosis, and infection susceptibility.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 34,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Cushing Syndrome and Disease",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_035",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Conn Syndrome",
      "question": "Conn syndrome results from excess secretion of which hormone?",
      "choices": {
        "A": "Cortisol",
        "B": "Epinephrine",
        "C": "Aldosterone",
        "D": "Adrenal androgen"
      },
      "correctAnswer": "C",
      "explanation": "Conn syndrome is primary aldosteronism, often caused by a zona glomerulosa tumor or cortical hyperplasia.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Conn syndrome is primary aldosteronism, often caused by a zona glomerulosa tumor or cortical hyperplasia.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 35,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Conn Syndrome",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_036",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Conn Syndrome",
      "question": "Which pattern is expected in primary aldosteronism?",
      "choices": {
        "A": "Hyperkalemia, acidosis, and hypotension",
        "B": "Hyponatremia, reduced volume, and hypoglycemia",
        "C": "Hyperkalemia, reduced volume, and tachycardia",
        "D": "Hypokalemia, mild alkalosis, and hypertension"
      },
      "correctAnswer": "D",
      "explanation": "Excess aldosterone increases sodium and volume retention while increasing potassium and hydrogen-ion loss.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Excess aldosterone increases sodium and volume retention while increasing potassium and hydrogen-ion loss.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 36,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Conn Syndrome",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "ADRN_SPRINT_037",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Adrenogenital Syndrome",
      "question": "An androgen-secreting adrenal cortical tumor is most likely to cause which change in an adult female?",
      "choices": {
        "A": "Virilization",
        "B": "Salt wasting only",
        "C": "Severe hypoglycemia only",
        "D": "Loss of all secondary sex characteristics"
      },
      "correctAnswer": "A",
      "explanation": "Excess adrenal androgens can produce male-pattern hair and other masculine physical traits in an adult female.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Excess adrenal androgens can produce male-pattern hair and other masculine physical traits in an adult female.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 37,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Adrenogenital Syndrome",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_038",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Adrenogenital Syndrome",
      "question": "Why can congenital adrenogenital syndrome produce both androgen excess and adrenal insufficiency?",
      "choices": {
        "A": "Catecholamines are converted directly into adrenal androgens.",
        "B": "Impaired cortisol and mineralocorticoid synthesis diverts steroid production toward androgens.",
        "C": "Excess aldosterone blocks androgen breakdown in the liver.",
        "D": "A pituitary tumor suppresses every adrenal steroid pathway equally."
      },
      "correctAnswer": "B",
      "explanation": "Defective conversion toward glucocorticoids and mineralocorticoids favors androgen formation while leaving deficient hormones that can contribute to adrenal crisis.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Defective conversion toward glucocorticoids and mineralocorticoids favors androgen formation while leaving deficient hormones that can contribute to adrenal crisis.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 38,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Adrenogenital Syndrome",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "ADRN_SPRINT_039",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Pheochromocytoma",
      "question": "Pheochromocytoma causes excessive secretion of which substances?",
      "choices": {
        "A": "Cortisol and aldosterone",
        "B": "Androgens and estrogens",
        "C": "ACTH and MSH",
        "D": "Epinephrine and norepinephrine"
      },
      "correctAnswer": "D",
      "explanation": "Pheochromocytoma is a catecholamine-secreting tumor of the adrenal medulla.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Pheochromocytoma is a catecholamine-secreting tumor of the adrenal medulla.",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 39,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Pheochromocytoma",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "ADRN_SPRINT_040",
      "unit": "adrenal",
      "conceptBlock": "Adrenal Hyperfunction",
      "subtopic": "Pheochromocytoma",
      "question": "Which finding belongs to the lecture's “5 H's” of pheochromocytoma?",
      "choices": {
        "A": "Hypotension",
        "B": "Hypometabolism",
        "C": "Hyperhidrosis",
        "D": "Hypoglycemia"
      },
      "correctAnswer": "C",
      "explanation": "The lecture identifies hypertension, headache, hyperhidrosis, hypermetabolism, and hyperglycemia as the “5 H's.”",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The lecture identifies hypertension, headache, hyperhidrosis, hypermetabolism, and hyperglycemia as the “5 H's.”",
      "bankId": "adrenal_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Adrenal Glands and Adrenal Hormones",
      "sourceOrder": 40,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 11 Lecture — Adrenal Glands and Adrenal Hormones; Week 11 Lecture Manual — Adrenal Gland",
        "broad_category": "Adrenal Hyperfunction",
        "concept_group": "Pheochromocytoma",
        "learning_level": "Applied Reinforcement"
      }
    }
  ]
};
window.ADRENAL_SPRINT_QUESTIONS = window.ADRENAL_SPRINT_BANK.questions;
