window.CALCIUM_PHOSPHATE_SPRINT_BANK = {
  "schemaVersion": "1.0.0",
  "bankId": "calcium_phosphate_sprint_v2_3",
  "bankType": "sprint",
  "mode": "learn",
  "sourceLecture": "Calcium and Phosphate Homeostasis",
  "questionCount": 50,
  "questions": [
    {
      "id": "CALC_SPRINT_001",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Distribution and Physiologic Roles",
      "question": "Where is most of the body's calcium stored?",
      "choices": {
        "A": "Bone",
        "B": "Plasma",
        "C": "Skeletal muscle",
        "D": "Extracellular fluid"
      },
      "correctAnswer": "A",
      "explanation": "About 99% of body calcium is stored in bone, leaving only small fractions in cells and extracellular fluid.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "About 99% of body calcium is stored in bone, leaving only small fractions in cells and extracellular fluid.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 1,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Distribution and Physiologic Roles",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_002",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Distribution and Physiologic Roles",
      "question": "Which plasma calcium fraction is physiologically active?",
      "choices": {
        "A": "Protein-bound calcium",
        "B": "Ionized calcium",
        "C": "Calcium complexed with anions",
        "D": "Calcium stored in hydroxyapatite"
      },
      "correctAnswer": "B",
      "explanation": "Ionized calcium makes up about half of plasma calcium and is the fraction that directly affects excitable tissues and hormone regulation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Ionized calcium makes up about half of plasma calcium and is the fraction that directly affects excitable tissues and hormone regulation.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 2,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Distribution and Physiologic Roles",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_003",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Distribution and Physiologic Roles",
      "question": "Phosphate contributes directly to which function?",
      "choices": {
        "A": "Carrying oxygen in hemoglobin",
        "B": "Producing thyroid hormone",
        "C": "Forming ATP and buffering acids",
        "D": "Initiating clotting without calcium"
      },
      "correctAnswer": "C",
      "explanation": "Phosphate contributes to energy transfer, intracellular compounds, bone mineral, and acid-base buffering.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Phosphate contributes to energy transfer, intracellular compounds, bone mineral, and acid-base buffering.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 3,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Distribution and Physiologic Roles",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_004",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Altered Calcium Levels",
      "question": "Why can hypocalcemia produce muscle spasms and tetany?",
      "choices": {
        "A": "Sodium channels open less easily",
        "B": "Potassium channels remain permanently closed",
        "C": "Acetylcholine release stops at motor end plates",
        "D": "Voltage-gated sodium channels become easier to activate"
      },
      "correctAnswer": "D",
      "explanation": "Low extracellular calcium reduces sodium-channel stabilization, increasing neuromuscular excitability and spontaneous firing.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low extracellular calcium reduces sodium-channel stabilization, increasing neuromuscular excitability and spontaneous firing.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 4,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Altered Calcium Levels",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_005",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Altered Calcium Levels",
      "question": "Tapping the facial nerve causes facial muscle contraction in a hypocalcemic patient. What is this finding called?",
      "choices": {
        "A": "Chvostek sign",
        "B": "Trousseau sign",
        "C": "Babinski sign",
        "D": "Romberg sign"
      },
      "correctAnswer": "A",
      "explanation": "Chvostek sign is facial muscle twitching after tapping over the facial nerve and reflects hypocalcemic neuromuscular excitability.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chvostek sign is facial muscle twitching after tapping over the facial nerve and reflects hypocalcemic neuromuscular excitability.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 5,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Altered Calcium Levels",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_006",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Altered Calcium Levels",
      "question": "Inflating a blood-pressure cuff triggers carpal spasm in a patient. Which disturbance best explains this response?",
      "choices": {
        "A": "Hypercalcemia",
        "B": "Hypocalcemia",
        "C": "Hyperphosphatemia alone",
        "D": "Vitamin D excess"
      },
      "correctAnswer": "B",
      "explanation": "Trousseau sign is carpal spasm caused by heightened neuromuscular excitability during hypocalcemia.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Trousseau sign is carpal spasm caused by heightened neuromuscular excitability during hypocalcemia.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 6,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Altered Calcium Levels",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_007",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Altered Calcium Levels",
      "question": "A patient with hypercalcemia would most likely show:",
      "choices": {
        "A": "Tetany and convulsions",
        "B": "Increased reflex activity",
        "C": "Constipation and sluggish reflexes",
        "D": "Prolonged neuromuscular excitability"
      },
      "correctAnswer": "C",
      "explanation": "High calcium depresses nervous-system activity and gastrointestinal motility; kidney stones may also occur.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "High calcium depresses nervous-system activity and gastrointestinal motility; kidney stones may also occur.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 7,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Altered Calcium Levels",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_008",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Absorption and Excretion",
      "question": "Efficient intestinal absorption of dietary calcium requires:",
      "choices": {
        "A": "Calcitonin",
        "B": "Aldosterone",
        "C": "Growth hormone",
        "D": "Active vitamin D"
      },
      "correctAnswer": "D",
      "explanation": "Calcium is poorly absorbed without vitamin D, which increases intestinal calcium-transport mechanisms.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Calcium is poorly absorbed without vitamin D, which increases intestinal calcium-transport mechanisms.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 8,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Absorption and Excretion",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_009",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcium and Phosphate Balance",
      "subtopic": "Absorption and Excretion",
      "question": "Where is hormonally regulated calcium reabsorption emphasized in the kidney?",
      "choices": {
        "A": "Late distal tubule and collecting duct",
        "B": "Glomerulus",
        "C": "Proximal tubule only",
        "D": "Descending limb only"
      },
      "correctAnswer": "A",
      "explanation": "Most filtered calcium is reabsorbed automatically, while PTH and vitamin D regulate later nephron calcium handling.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Most filtered calcium is reabsorbed automatically, while PTH and vitamin D regulate later nephron calcium handling.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 9,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcium and Phosphate Balance",
        "concept_group": "Absorption and Excretion",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_010",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Composition and Calcification",
      "question": "Which combination best describes the major physical components of bone?",
      "choices": {
        "A": "Elastin, sodium chloride, and phosphate",
        "B": "Collagen, ground substance, and hydroxyapatite",
        "C": "Keratin, calcium carbonate, and water",
        "D": "Collagen, glycogen, and potassium chloride"
      },
      "correctAnswer": "B",
      "explanation": "Bone combines an organic collagen-rich matrix with crystalline hydroxyapatite, producing tensile and compressive strength.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Bone combines an organic collagen-rich matrix with crystalline hydroxyapatite, producing tensile and compressive strength.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 10,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Composition and Calcification",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_011",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Composition and Calcification",
      "question": "What is osteoid?",
      "choices": {
        "A": "Mature mineral crystals released by osteoclasts",
        "B": "Fluid stored inside trabecular spaces",
        "C": "Unmineralized organic matrix produced by osteoblasts",
        "D": "Calcified cartilage produced by osteocytes"
      },
      "correctAnswer": "C",
      "explanation": "Osteoblasts first secrete collagen and ground substance as osteoid; calcium salts then precipitate within it.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Osteoblasts first secrete collagen and ground substance as osteoid; calcium salts then precipitate within it.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 11,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Composition and Calcification",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_012",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Composition and Calcification",
      "question": "Unwanted calcium-phosphate precipitation is normally inhibited by:",
      "choices": {
        "A": "Calbindin",
        "B": "Calcitonin",
        "C": "Osteocalcin",
        "D": "Pyrophosphate"
      },
      "correctAnswer": "D",
      "explanation": "Pyrophosphate restrains mineral precipitation until local bone-regulating mechanisms permit calcification.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Pyrophosphate restrains mineral precipitation until local bone-regulating mechanisms permit calcification.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 12,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Composition and Calcification",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_013",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Composition and Calcification",
      "question": "What is the effect of tissue-nonspecific alkaline phosphatase on bone mineralization?",
      "choices": {
        "A": "It breaks down pyrophosphate and favors mineralization",
        "B": "It produces pyrophosphate and inhibits mineralization",
        "C": "It dissolves hydroxyapatite during resorption",
        "D": "It prevents osteoblasts from producing osteoid"
      },
      "correctAnswer": "A",
      "explanation": "TNAP removes inhibitory pyrophosphate, making calcium-phosphate deposition and hydroxyapatite formation more likely.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "TNAP removes inhibitory pyrophosphate, making calcium-phosphate deposition and hydroxyapatite formation more likely.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 13,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Composition and Calcification",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_014",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Cells and Remodeling",
      "question": "New bone matrix is primarily deposited by:",
      "choices": {
        "A": "Osteoclast",
        "B": "Osteoblast",
        "C": "Osteocyte",
        "D": "Chondrocyte"
      },
      "correctAnswer": "B",
      "explanation": "Osteoblasts form osteoid and support its mineralization, whereas osteoclasts resorb bone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Osteoblasts form osteoid and support its mineralization, whereas osteoclasts resorb bone.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 14,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Cells and Remodeling",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_015",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Cells and Remodeling",
      "question": "How does an osteoclast resorb bone?",
      "choices": {
        "A": "It secretes osteoid over the mineral surface",
        "B": "It transports calcium into hydroxyapatite crystals",
        "C": "It releases acid and enzymes at a ruffled border",
        "D": "It converts collagen directly into phosphate"
      },
      "correctAnswer": "C",
      "explanation": "Osteoclasts create a sealed resorption area where acid dissolves mineral and enzymes digest organic matrix.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Osteoclasts create a sealed resorption area where acid dissolves mineral and enzymes digest organic matrix.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 15,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Cells and Remodeling",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_016",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "Bone Cells and Remodeling",
      "question": "Continuous bone remodeling requires a balance between which processes?",
      "choices": {
        "A": "Cartilage growth and tendon shortening",
        "B": "Calcium filtration and phosphate secretion",
        "C": "Collagen absorption and vitamin D excretion",
        "D": "Osteoblast deposition and osteoclast resorption"
      },
      "correctAnswer": "D",
      "explanation": "Normal bone mass depends on coordinated replacement of resorbed bone with newly deposited bone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Normal bone mass depends on coordinated replacement of resorbed bone with newly deposited bone.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 16,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "Bone Cells and Remodeling",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_017",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "RANKL and OPG Regulation",
      "question": "How does PTH promote osteoclast activity even though osteoclasts lack PTH receptors?",
      "choices": {
        "A": "It stimulates osteoblast-lineage cells to express RANKL",
        "B": "It converts osteocytes directly into osteoclasts",
        "C": "It blocks all osteoblast signaling",
        "D": "It binds hydroxyapatite and releases acid"
      },
      "correctAnswer": "A",
      "explanation": "PTH acts indirectly through osteoblast-lineage cells; RANKL promotes osteoclast formation and activation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTH acts indirectly through osteoblast-lineage cells; RANKL promotes osteoclast formation and activation.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 17,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "RANKL and OPG Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_018",
      "unit": "calcium-phosphate",
      "conceptBlock": "Bone Structure and Remodeling",
      "subtopic": "RANKL and OPG Regulation",
      "question": "Osteoprotegerin limits bone resorption because:",
      "choices": {
        "A": "It activates RANK on osteoclast precursors",
        "B": "It acts as a decoy receptor for RANKL",
        "C": "It increases PTH secretion from chief cells",
        "D": "It mineralizes osteoid directly"
      },
      "correctAnswer": "B",
      "explanation": "OPG binds RANKL before it reaches RANK, thereby limiting osteoclast development and bone resorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "OPG binds RANKL before it reaches RANK, thereby limiting osteoclast development and bone resorption.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 18,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Bone Structure and Remodeling",
        "concept_group": "RANKL and OPG Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_019",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Activation Pathway",
      "question": "The liver converts vitamin D into:",
      "choices": {
        "A": "1,25-dihydroxycholecalciferol",
        "B": "Parathyroid hormone",
        "C": "25-hydroxycholecalciferol",
        "D": "Hydroxyapatite"
      },
      "correctAnswer": "C",
      "explanation": "The liver produces 25-hydroxycholecalciferol, which is later converted by the kidney to active calcitriol.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The liver produces 25-hydroxycholecalciferol, which is later converted by the kidney to active calcitriol.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 19,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Activation Pathway",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_020",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Activation Pathway",
      "question": "Which organ performs the final activation step that produces calcitriol?",
      "choices": {
        "A": "Skin",
        "B": "Liver",
        "C": "Parathyroid gland",
        "D": "Kidney"
      },
      "correctAnswer": "D",
      "explanation": "The kidney converts 25-hydroxycholecalciferol to 1,25-dihydroxycholecalciferol, the active hormone calcitriol.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The kidney converts 25-hydroxycholecalciferol to 1,25-dihydroxycholecalciferol, the active hormone calcitriol.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 20,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Activation Pathway",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_021",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Activation Pathway",
      "question": "What stimulates renal production of active vitamin D when plasma calcium falls?",
      "choices": {
        "A": "PTH",
        "B": "Calcitonin",
        "C": "Insulin",
        "D": "Aldosterone"
      },
      "correctAnswer": "A",
      "explanation": "Low calcium raises PTH, which stimulates the kidney's final vitamin D activation step.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low calcium raises PTH, which stimulates the kidney's final vitamin D activation step.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 21,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Activation Pathway",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_022",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Physiologic Actions",
      "question": "What is the principal effect of active vitamin D on the intestine?",
      "choices": {
        "A": "Decreased calcium and phosphate absorption",
        "B": "Increased calcium and phosphate absorption",
        "C": "Increased calcium secretion into the lumen",
        "D": "Decreased production of transport proteins"
      },
      "correctAnswer": "B",
      "explanation": "Calcitriol increases intestinal transport mechanisms for both calcium and phosphate.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Calcitriol increases intestinal transport mechanisms for both calcium and phosphate.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 22,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Physiologic Actions",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_023",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Physiologic Actions",
      "question": "Active vitamin D increases which intestinal calcium-transport protein?",
      "choices": {
        "A": "Albumin",
        "B": "Osteoprotegerin",
        "C": "Calbindin",
        "D": "Thyroglobulin"
      },
      "correctAnswer": "C",
      "explanation": "Calcitriol promotes calbindin and other transport proteins that move absorbed calcium through intestinal cells.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Calcitriol promotes calbindin and other transport proteins that move absorbed calcium through intestinal cells.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 23,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Physiologic Actions",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_024",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Physiologic Actions",
      "question": "Which statement best describes vitamin D's effect on bone?",
      "choices": {
        "A": "It has no relationship to bone mineral handling",
        "B": "It always prevents any calcium release from bone",
        "C": "It directly replaces collagen in the bone matrix",
        "D": "Its effect depends partly on amount and physiologic conditions"
      },
      "correctAnswer": "D",
      "explanation": "Vitamin D supports mineralization at appropriate levels but can promote bone resorption in larger amounts and in conjunction with PTH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Vitamin D supports mineralization at appropriate levels but can promote bone resorption in larger amounts and in conjunction with PTH.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 24,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Physiologic Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_025",
      "unit": "calcium-phosphate",
      "conceptBlock": "Vitamin D",
      "subtopic": "Physiologic Actions",
      "question": "Vitamin D acts through which general receptor mechanism?",
      "choices": {
        "A": "Binding an intracellular receptor that influences transcription",
        "B": "Opening a ligand-gated sodium channel",
        "C": "Activating a receptor only on the cell membrane",
        "D": "Entering synaptic vesicles for release"
      },
      "correctAnswer": "A",
      "explanation": "Active vitamin D is steroid-like and regulates gene expression through an intracellular receptor.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Active vitamin D is steroid-like and regulates gene expression through an intracellular receptor.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 25,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Vitamin D",
        "concept_group": "Physiologic Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_026",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Source and Secretion",
      "question": "Parathyroid hormone is secreted by:",
      "choices": {
        "A": "Thyroid follicular cells",
        "B": "Parathyroid chief cells",
        "C": "Parathyroid oxyphil cells only",
        "D": "Thyroid parafollicular cells"
      },
      "correctAnswer": "B",
      "explanation": "Chief cells are the primary PTH-secreting cells of the parathyroid glands.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chief cells are the primary PTH-secreting cells of the parathyroid glands.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 26,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Source and Secretion",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_027",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Source and Secretion",
      "question": "PTH secretion increases directly in response to:",
      "choices": {
        "A": "Increased ionized calcium",
        "B": "Increased calcitonin alone",
        "C": "Decreased ionized calcium",
        "D": "Decreased plasma sodium"
      },
      "correctAnswer": "C",
      "explanation": "The calcium-sensing receptor detects falling extracellular calcium and permits increased PTH release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The calcium-sensing receptor detects falling extracellular calcium and permits increased PTH release.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 27,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Source and Secretion",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_028",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Bone Actions",
      "question": "What is the overall effect of PTH on calcium movement from bone?",
      "choices": {
        "A": "It permanently traps calcium in osteoid",
        "B": "It prevents all osteoclast formation",
        "C": "It converts calcium into phosphate",
        "D": "It favors calcium release into extracellular fluid"
      },
      "correctAnswer": "D",
      "explanation": "PTH increases bone resorption through rapid and slower mechanisms, helping raise extracellular calcium.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTH increases bone resorption through rapid and slower mechanisms, helping raise extracellular calcium.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 28,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Bone Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_029",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Bone Actions",
      "question": "Compared with rapid calcium mobilization, which PTH effect develops more slowly?",
      "choices": {
        "A": "Activation and proliferation of osteoclasts",
        "B": "Filtration of calcium at the glomerulus",
        "C": "Formation of calcitonin by chief cells",
        "D": "Production of sweat by eccrine glands"
      },
      "correctAnswer": "A",
      "explanation": "PTH can mobilize calcium rapidly, while increased osteoclast formation and activity develops over a longer period.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTH can mobilize calcium rapidly, while increased osteoclast formation and activity develops over a longer period.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 29,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Bone Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_030",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Bone Actions",
      "question": "PTH increases bone resorption. Which pair of ions initially enters extracellular fluid from bone?",
      "choices": {
        "A": "Sodium and chloride",
        "B": "Calcium and phosphate",
        "C": "Potassium and bicarbonate",
        "D": "Magnesium and sulfate only"
      },
      "correctAnswer": "B",
      "explanation": "Hydroxyapatite dissolution releases both calcium and phosphate, although PTH later promotes renal phosphate loss.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Hydroxyapatite dissolution releases both calcium and phosphate, although PTH later promotes renal phosphate loss.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 30,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Bone Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_031",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Kidney and Intestinal Actions",
      "question": "How does PTH affect renal calcium handling?",
      "choices": {
        "A": "It decreases calcium reabsorption",
        "B": "It prevents calcium filtration",
        "C": "It increases calcium reabsorption",
        "D": "It converts calcium to phosphate"
      },
      "correctAnswer": "C",
      "explanation": "PTH conserves calcium by increasing its reabsorption in the late distal nephron and collecting system.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTH conserves calcium by increasing its reabsorption in the late distal nephron and collecting system.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 31,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Kidney and Intestinal Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_032",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Kidney and Intestinal Actions",
      "question": "How does PTH affect renal phosphate handling?",
      "choices": {
        "A": "It increases phosphate reabsorption",
        "B": "It decreases phosphate excretion",
        "C": "It prevents phosphate filtration",
        "D": "It decreases phosphate reabsorption"
      },
      "correctAnswer": "D",
      "explanation": "PTH causes phosphaturia by reducing proximal tubular phosphate reabsorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTH causes phosphaturia by reducing proximal tubular phosphate reabsorption.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 32,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Kidney and Intestinal Actions",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_033",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Kidney and Intestinal Actions",
      "question": "PTH releases calcium and phosphate from bone, yet plasma phosphate can fall. What best explains this result?",
      "choices": {
        "A": "PTH increases renal phosphate excretion",
        "B": "PTH prevents phosphate from leaving bone",
        "C": "PTH converts phosphate into calcium",
        "D": "PTH blocks glomerular filtration"
      },
      "correctAnswer": "A",
      "explanation": "The renal phosphaturic effect can outweigh phosphate released from bone, producing low plasma phosphate despite bone resorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The renal phosphaturic effect can outweigh phosphate released from bone, producing low plasma phosphate despite bone resorption.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 33,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Kidney and Intestinal Actions",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "CALC_SPRINT_034",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Kidney and Intestinal Actions",
      "question": "How does PTH increase intestinal calcium absorption?",
      "choices": {
        "A": "It directly opens calcium channels in enterocytes",
        "B": "It stimulates renal activation of vitamin D",
        "C": "It causes the liver to secrete calcitonin",
        "D": "It increases intestinal phosphate secretion"
      },
      "correctAnswer": "B",
      "explanation": "PTH acts indirectly on the intestine by increasing calcitriol production, which raises intestinal calcium absorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTH acts indirectly on the intestine by increasing calcitriol production, which raises intestinal calcium absorption.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 34,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Kidney and Intestinal Actions",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "CALC_SPRINT_035",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Feedback Regulation",
      "question": "What happens to PTH secretion when the calcium-sensing receptor detects high extracellular calcium?",
      "choices": {
        "A": "PTH secretion increases",
        "B": "PTH changes into calcitonin",
        "C": "PTH secretion decreases",
        "D": "PTH secretion becomes unrelated to calcium"
      },
      "correctAnswer": "C",
      "explanation": "High calcium activates CaSR signaling that suppresses PTH release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "High calcium activates CaSR signaling that suppresses PTH release.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 35,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Feedback Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_036",
      "unit": "calcium-phosphate",
      "conceptBlock": "Parathyroid Hormone",
      "subtopic": "Feedback Regulation",
      "question": "Persistent parathyroid stimulation and gland enlargement are most likely during:",
      "choices": {
        "A": "Persistently high dietary calcium",
        "B": "Excess active vitamin D",
        "C": "Prolonged suppression of PTH",
        "D": "Persistently low extracellular calcium"
      },
      "correctAnswer": "D",
      "explanation": "Chronic low calcium, including that associated with vitamin D deficiency, persistently stimulates PTH secretion and gland hypertrophy.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chronic low calcium, including that associated with vitamin D deficiency, persistently stimulates PTH secretion and gland hypertrophy.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 36,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Parathyroid Hormone",
        "concept_group": "Feedback Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_037",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcitonin and Integrated Control",
      "subtopic": "Calcitonin",
      "question": "Calcitonin is released by:",
      "choices": {
        "A": "Thyroid parafollicular cells",
        "B": "Thyroid follicular cells",
        "C": "Parathyroid chief cells",
        "D": "Pituitary thyrotrophs"
      },
      "correctAnswer": "A",
      "explanation": "Parafollicular C cells secrete calcitonin when plasma calcium rises.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Parafollicular C cells secrete calcitonin when plasma calcium rises.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 37,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcitonin and Integrated Control",
        "concept_group": "Calcitonin",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_038",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcitonin and Integrated Control",
      "subtopic": "Calcitonin",
      "question": "What is calcitonin's immediate effect on bone?",
      "choices": {
        "A": "Increased osteoclast activity",
        "B": "Decreased osteoclast activity",
        "C": "Increased RANKL signaling",
        "D": "Decreased osteoblast activity"
      },
      "correctAnswer": "B",
      "explanation": "Calcitonin rapidly inhibits osteoclast activity and favors movement away from bone resorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Calcitonin rapidly inhibits osteoclast activity and favors movement away from bone resorption.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 38,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcitonin and Integrated Control",
        "concept_group": "Calcitonin",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_039",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcitonin and Integrated Control",
      "subtopic": "Calcitonin",
      "question": "Why is calcitonin usually a minor regulator of daily calcium balance in adults?",
      "choices": {
        "A": "It is not produced after childhood",
        "B": "It raises calcium rather than lowering it",
        "C": "PTH and vitamin D provide the dominant control",
        "D": "It acts only on intestinal sodium"
      },
      "correctAnswer": "C",
      "explanation": "Calcitonin can oppose bone resorption, but PTH and vitamin D are more important for routine adult calcium homeostasis.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Calcitonin can oppose bone resorption, but PTH and vitamin D are more important for routine adult calcium homeostasis.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 39,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcitonin and Integrated Control",
        "concept_group": "Calcitonin",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_040",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcitonin and Integrated Control",
      "subtopic": "Integrated Calcium Control",
      "question": "If ionized calcium falls, which hormonal pattern is expected?",
      "choices": {
        "A": "Decreased PTH and decreased calcitriol",
        "B": "Increased calcitonin and decreased PTH",
        "C": "Increased calcitonin and decreased calcitriol",
        "D": "Increased PTH and increased calcitriol"
      },
      "correctAnswer": "D",
      "explanation": "Low calcium raises PTH, which conserves calcium and stimulates renal production of calcitriol.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low calcium raises PTH, which conserves calcium and stimulates renal production of calcitriol.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 40,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcitonin and Integrated Control",
        "concept_group": "Integrated Calcium Control",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "CALC_SPRINT_041",
      "unit": "calcium-phosphate",
      "conceptBlock": "Calcitonin and Integrated Control",
      "subtopic": "Integrated Calcium Control",
      "question": "After a calcium-rich meal, which response most directly opposes a further rise in plasma calcium?",
      "choices": {
        "A": "Increased calcitonin secretion",
        "B": "Increased PTH secretion",
        "C": "Increased osteoclast formation",
        "D": "Increased renal vitamin D activation"
      },
      "correctAnswer": "A",
      "explanation": "High calcium stimulates calcitonin and suppresses PTH, shifting regulation toward reduced bone resorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "High calcium stimulates calcitonin and suppresses PTH, shifting regulation toward reduced bone resorption.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 41,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Calcitonin and Integrated Control",
        "concept_group": "Integrated Calcium Control",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "CALC_SPRINT_042",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Osteoporosis",
      "question": "Osteoporosis develops when:",
      "choices": {
        "A": "Bone formation exceeds bone resorption",
        "B": "Bone resorption exceeds bone formation",
        "C": "Osteoid production stops all mineral release",
        "D": "Calcium absorption always becomes excessive"
      },
      "correctAnswer": "B",
      "explanation": "Osteoporosis develops when bone deposition fails to keep pace with resorption, reducing bone mass and fracture resistance.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Osteoporosis develops when bone deposition fails to keep pace with resorption, reducing bone mass and fracture resistance.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 42,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Osteoporosis",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_043",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Osteoporosis",
      "question": "Following menopause, osteoporosis risk rises partly because of:",
      "choices": {
        "A": "Increased estrogen stimulation of OPG",
        "B": "Increased collagen production from vitamin C",
        "C": "Decreased estrogen support of OPG",
        "D": "Decreased osteoclast responsiveness to RANKL"
      },
      "correctAnswer": "C",
      "explanation": "Loss of estrogen reduces anti-resorptive support, allowing osteoclast activity to contribute to bone loss.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Loss of estrogen reduces anti-resorptive support, allowing osteoclast activity to contribute to bone loss.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 43,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Osteoporosis",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_044",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Hyperparathyroidism",
      "question": "A patient with primary hyperparathyroidism most likely has:",
      "choices": {
        "A": "Low calcium, high phosphate, low PTH",
        "B": "High calcium, high phosphate, low PTH",
        "C": "Low calcium, low phosphate, low PTH",
        "D": "High calcium, low phosphate, high PTH"
      },
      "correctAnswer": "D",
      "explanation": "Excess autonomous PTH raises calcium while increasing renal phosphate loss.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Excess autonomous PTH raises calcium while increasing renal phosphate loss.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 44,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Hyperparathyroidism",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_045",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Hyperparathyroidism",
      "question": "Which finding is associated with primary hyperparathyroidism?",
      "choices": {
        "A": "Kidney stones and reduced bone strength",
        "B": "Tetany with suppressed bone resorption",
        "C": "Low urine calcium from absent PTH",
        "D": "Increased phosphate retention with high PTH"
      },
      "correctAnswer": "A",
      "explanation": "Chronic hypercalcemia and PTH-driven bone resorption contribute to “stones” and “bones,” along with gastrointestinal and neuropsychiatric symptoms.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chronic hypercalcemia and PTH-driven bone resorption contribute to “stones” and “bones,” along with gastrointestinal and neuropsychiatric symptoms.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 45,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Hyperparathyroidism",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_046",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Hyperparathyroidism",
      "question": "Secondary hyperparathyroidism commonly results from:",
      "choices": {
        "A": "Autonomous calcitonin secretion",
        "B": "Persistent hypocalcemic stimulation",
        "C": "Excess dietary calcium",
        "D": "Destruction of all osteoclasts"
      },
      "correctAnswer": "B",
      "explanation": "Vitamin D deficiency or chronic renal disease can lower effective calcium availability, appropriately stimulating sustained PTH secretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Vitamin D deficiency or chronic renal disease can lower effective calcium availability, appropriately stimulating sustained PTH secretion.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 46,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Hyperparathyroidism",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_047",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Hypoparathyroidism",
      "question": "Following thyroid surgery, a patient develops tingling and carpal spasm. Which disturbance is most likely?",
      "choices": {
        "A": "Excess PTH causing hypercalcemia",
        "B": "Excess calcitonin causing hyperphosphatemia alone",
        "C": "Low PTH causing hypocalcemia",
        "D": "High vitamin D causing neuromuscular depression"
      },
      "correctAnswer": "C",
      "explanation": "Accidental parathyroid injury can reduce PTH, producing hypocalcemia and neuromuscular hyperexcitability.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Accidental parathyroid injury can reduce PTH, producing hypocalcemia and neuromuscular hyperexcitability.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 47,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Hypoparathyroidism",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "CALC_SPRINT_048",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Hypoparathyroidism",
      "question": "Why can phosphate rise in hypoparathyroidism?",
      "choices": {
        "A": "Loss of PTH blocks intestinal phosphate absorption",
        "B": "Calcitonin converts calcium into phosphate",
        "C": "Vitamin D directly secretes phosphate into plasma",
        "D": "Loss of PTH increases renal phosphate reabsorption"
      },
      "correctAnswer": "D",
      "explanation": "Without PTH's phosphaturic effect, the kidney retains more phosphate while calcium conservation and calcitriol activation decline.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Without PTH's phosphaturic effect, the kidney retains more phosphate while calcium conservation and calcitriol activation decline.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 48,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Hypoparathyroidism",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "CALC_SPRINT_049",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Rickets and Osteomalacia",
      "question": "What distinguishes rickets from osteomalacia?",
      "choices": {
        "A": "Rickets occurs in children, while osteomalacia occurs in adults",
        "B": "Rickets affects adults, while osteomalacia affects children",
        "C": "Rickets is caused only by excess PTH",
        "D": "Osteomalacia results only from calcitonin excess"
      },
      "correctAnswer": "A",
      "explanation": "Both involve inadequate bone mineralization, but rickets affects growing childhood bone and osteomalacia affects adult bone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Both involve inadequate bone mineralization, but rickets affects growing childhood bone and osteomalacia affects adult bone.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 49,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Rickets and Osteomalacia",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "CALC_SPRINT_050",
      "unit": "calcium-phosphate",
      "conceptBlock": "Clinical Disorders",
      "subtopic": "Rickets and Osteomalacia",
      "question": "Why can fat malabsorption contribute to osteomalacia?",
      "choices": {
        "A": "It increases renal PTH destruction",
        "B": "It reduces absorption of fat-soluble vitamin D",
        "C": "It causes excessive calcitonin release",
        "D": "It converts osteoblasts into osteoclasts"
      },
      "correctAnswer": "B",
      "explanation": "Poor fat absorption can reduce vitamin D uptake and calcium availability, impairing adult bone mineralization.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Poor fat absorption can reduce vitamin D uptake and calcium availability, impairing adult bone mineralization.",
      "bankId": "calcium_phosphate_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Calcium and Phosphate Homeostasis",
      "sourceOrder": 50,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 12 Lecture — Calcium and Phosphate Homeostasis",
        "broad_category": "Clinical Disorders",
        "concept_group": "Rickets and Osteomalacia",
        "learning_level": "Applied Reinforcement"
      }
    }
  ]
};
window.CALCIUM_PHOSPHATE_SPRINT_QUESTIONS = window.CALCIUM_PHOSPHATE_SPRINT_BANK.questions;
