window.LAB11_SPRINT_BANK = {
  "schemaVersion": "1.0.0",
  "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
  "bankType": "sprint",
  "contentGroup": "labs",
  "mode": "labs",
  "sourceLecture": "Lab 11: Thyroid and Adrenal Hormones",
  "questionCount": 60,
  "questions": [
    {
      "id": "LAB11_001",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Axis Organization",
      "question": "Which sequence correctly traces the HPT axis?",
      "choices": {
        "A": "TRH -> TSH -> T3/T4",
        "B": "TSH -> TRH -> T3/T4",
        "C": "T3/T4 -> TRH -> TSH",
        "D": "TRH -> T3/T4 -> TSH"
      },
      "correctAnswer": "A",
      "explanation": "Hypothalamic TRH stimulates anterior-pituitary TSH, which stimulates thyroid T3 and T4 secretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Hypothalamic TRH stimulates anterior-pituitary TSH, which stimulates thyroid T3 and T4 secretion.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 1,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Axis Organization",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_002",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Axis Organization",
      "question": "What is the main endocrine target of TSH?",
      "choices": {
        "A": "Anterior pituitary",
        "B": "Thyroid gland",
        "C": "Hypothalamus",
        "D": "Adrenal cortex"
      },
      "correctAnswer": "B",
      "explanation": "TSH travels from the anterior pituitary to the thyroid and stimulates thyroid-hormone synthesis and release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "TSH travels from the anterior pituitary to the thyroid and stimulates thyroid-hormone synthesis and release.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 2,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Axis Organization",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_003",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroid Hormone Effects",
      "question": "What two effects of thyroid hormone receive the strongest emphasis in the lab?",
      "choices": {
        "A": "Increased aldosterone and potassium excretion",
        "B": "Decreased oxygen use and body temperature",
        "C": "Increased basal metabolic rate and heat production",
        "D": "Decreased growth and central nervous system development"
      },
      "correctAnswer": "C",
      "explanation": "Thyroid hormone raises basal metabolic rate and heat production and also supports growth and nervous-system development.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroid hormone raises basal metabolic rate and heat production and also supports growth and nervous-system development.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 3,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroid Hormone Effects",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_004",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "T4 and T3",
      "question": "How does much of the T4 released by the thyroid become more active in target cells?",
      "choices": {
        "A": "TSH converts T4 to T3",
        "B": "Peroxidase converts T4 to TSH",
        "C": "TRH converts T4 to T3",
        "D": "Deiodinase converts T4 to T3"
      },
      "correctAnswer": "D",
      "explanation": "Target-cell deiodinase removes iodine from T4 to form the more active T3.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Target-cell deiodinase removes iodine from T4 to form the more active T3.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 4,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "T4 and T3",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_005",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Negative Feedback",
      "question": "When circulating thyroid hormone rises, what happens to TRH and TSH under normal feedback?",
      "choices": {
        "A": "Both decrease",
        "B": "Both increase",
        "C": "TRH increases while TSH decreases",
        "D": "TRH decreases while TSH increases"
      },
      "correctAnswer": "A",
      "explanation": "Higher thyroid hormone increases negative feedback at the hypothalamus and anterior pituitary, lowering TRH and TSH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Higher thyroid hormone increases negative feedback at the hypothalamus and anterior pituitary, lowering TRH and TSH.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 5,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Negative Feedback",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_006",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Negative Feedback",
      "question": "A fall in thyroid hormone produces which normal upstream response?",
      "choices": {
        "A": "TRH and TSH decrease",
        "B": "TRH and TSH increase",
        "C": "TRH decreases while TSH increases",
        "D": "TRH increases while TSH decreases"
      },
      "correctAnswer": "B",
      "explanation": "Low thyroid hormone removes feedback inhibition, allowing both TRH and TSH to rise.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low thyroid hormone removes feedback inhibition, allowing both TRH and TSH to rise.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 6,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Negative Feedback",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_007",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Lesion Localization",
      "question": "Which pattern most strongly suggests primary thyroid failure?",
      "choices": {
        "A": "Low free T4 with low TSH",
        "B": "High free T4 with low TSH",
        "C": "Low free T4 with high TSH",
        "D": "High free T4 with high TSH"
      },
      "correctAnswer": "C",
      "explanation": "A failing thyroid produces too little T4, while the intact pituitary raises TSH in an attempt to stimulate it.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "A failing thyroid produces too little T4, while the intact pituitary raises TSH in an attempt to stimulate it.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 7,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Lesion Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_008",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Lesion Localization",
      "question": "Which pattern best fits reduced pituitary stimulation of an otherwise intact thyroid?",
      "choices": {
        "A": "Low free T4 with high TSH",
        "B": "High free T4 with low TSH",
        "C": "High free T4 with high TSH",
        "D": "Low free T4 with low TSH"
      },
      "correctAnswer": "D",
      "explanation": "Pituitary failure lowers TSH, so the thyroid receives inadequate stimulation and free T4 falls.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Pituitary failure lowers TSH, so the thyroid receives inadequate stimulation and free T4 falls.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 8,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Lesion Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_009",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Metabolic Consequences",
      "question": "Why does oxygen consumption fall in hypothyroidism?",
      "choices": {
        "A": "Lower thyroid hormone reduces basal metabolic activity",
        "B": "Low TSH directly blocks oxygen binding to hemoglobin",
        "C": "High TRH prevents oxygen delivery to tissues",
        "D": "Low T4 increases cellular heat production"
      },
      "correctAnswer": "A",
      "explanation": "Oxygen consumption follows metabolic demand, so the reduced basal metabolic rate of hypothyroidism lowers oxygen use.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Oxygen consumption follows metabolic demand, so the reduced basal metabolic rate of hypothyroidism lowers oxygen use.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 9,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Metabolic Consequences",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_010",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Exogenous Hormone and RAIU",
      "question": "A patient has high free T4 and low TSH. Which finding favors Graves disease over exogenous levothyroxine use?",
      "choices": {
        "A": "Low diffuse radioactive iodine uptake",
        "B": "High diffuse radioactive iodine uptake",
        "C": "Absent TSH-receptor stimulation",
        "D": "Progressively falling oxygen consumption"
      },
      "correctAnswer": "B",
      "explanation": "Graves disease actively stimulates the thyroid to take up iodine, whereas exogenous T4 suppresses TSH and makes the gland relatively inactive.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Graves disease actively stimulates the thyroid to take up iodine, whereas exogenous T4 suppresses TSH and makes the gland relatively inactive.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 10,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Exogenous Hormone and RAIU",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_011",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroidectomy",
      "question": "What happens to thyroid-hormone production after a total thyroidectomy without replacement?",
      "choices": {
        "A": "It rises because TSH increases",
        "B": "It remains normal through pituitary compensation",
        "C": "It falls toward zero",
        "D": "It switches entirely to adrenal production"
      },
      "correctAnswer": "C",
      "explanation": "Removing the thyroid removes the tissue that produces T3 and T4, so upstream stimulation cannot restore output.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Removing the thyroid removes the tissue that produces T3 and T4, so upstream stimulation cannot restore output.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 11,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroidectomy",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_012",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroidectomy",
      "question": "Why does TSH rise progressively after total thyroidectomy?",
      "choices": {
        "A": "Rising T4 directly stimulates the pituitary",
        "B": "The absent thyroid begins secreting TRH",
        "C": "The adrenal cortex replaces thyroid feedback",
        "D": "Falling T4 removes pituitary and hypothalamic feedback"
      },
      "correctAnswer": "D",
      "explanation": "As residual T4 declines, negative feedback weakens and TRH-driven pituitary TSH secretion rises.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "As residual T4 declines, negative feedback weakens and TRH-driven pituitary TSH secretion rises.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 12,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroidectomy",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_013",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroidectomy",
      "question": "What happens if TSH is given to a patient with no thyroid tissue?",
      "choices": {
        "A": "T3 and T4 remain very low",
        "B": "T3 rises while T4 stays low",
        "C": "T4 rises while T3 stays low",
        "D": "Both hormones return immediately to normal"
      },
      "correctAnswer": "A",
      "explanation": "TSH requires functioning thyroid tissue; without that target gland, it cannot produce a thyroid-hormone response.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "TSH requires functioning thyroid tissue; without that target gland, it cannot produce a thyroid-hormone response.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 13,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroidectomy",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_014",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroid Replacement",
      "question": "How should TSH change after levothyroxine is started in a thyroidectomized patient?",
      "choices": {
        "A": "It should increase without limit",
        "B": "It should gradually decrease",
        "C": "It should remain fixed at the pre-treatment level",
        "D": "It should become the source of circulating T4"
      },
      "correctAnswer": "B",
      "explanation": "Levothyroxine restores thyroid-hormone feedback, so pituitary TSH gradually falls toward its target range.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Levothyroxine restores thyroid-hormone feedback, so pituitary TSH gradually falls toward its target range.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 14,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroid Replacement",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_015",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroidectomy",
      "question": "Why does TSH not spike immediately at the moment of thyroid removal?",
      "choices": {
        "A": "The pituitary stores enough T3 for several weeks",
        "B": "TRH cannot enter the portal circulation after surgery",
        "C": "Residual circulating T4 continues to provide feedback",
        "D": "TSH secretion requires thyroid peroxidase"
      },
      "correctAnswer": "C",
      "explanation": "T4 has a long circulating half-life, so remaining hormone temporarily continues to restrain TSH after surgery.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "T4 has a long circulating half-life, so remaining hormone temporarily continues to restrain TSH after surgery.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 15,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroidectomy",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_016",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroid Drug Effects",
      "question": "Propylthiouracil lowers active thyroid hormone through which two lab-supported actions?",
      "choices": {
        "A": "Increased TSH release and increased iodine uptake",
        "B": "Reduced TRH release and increased T3 secretion",
        "C": "Increased peroxidase activity and reduced T4 clearance",
        "D": "Reduced thyroid synthesis and reduced T4-to-T3 conversion"
      },
      "correctAnswer": "D",
      "explanation": "PTU inhibits thyroid peroxidase in the gland and deiodinase-mediated T4-to-T3 conversion in peripheral tissues.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "PTU inhibits thyroid peroxidase in the gland and deiodinase-mediated T4-to-T3 conversion in peripheral tissues.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 16,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroid Drug Effects",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_017",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Axis Organization",
      "question": "Starting at the hypothalamus, what is the order of the HPA axis?",
      "choices": {
        "A": "CRH -> ACTH -> cortisol",
        "B": "ACTH -> CRH -> cortisol",
        "C": "Cortisol -> ACTH -> CRH",
        "D": "CRH -> cortisol -> ACTH"
      },
      "correctAnswer": "A",
      "explanation": "Hypothalamic CRH stimulates pituitary ACTH, which stimulates adrenal-cortical cortisol secretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Hypothalamic CRH stimulates pituitary ACTH, which stimulates adrenal-cortical cortisol secretion.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 17,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Axis Organization",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_018",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Cortisol Rhythm",
      "question": "When is cortisol normally highest during the day?",
      "choices": {
        "A": "Near the onset of sleep",
        "B": "Early morning",
        "C": "At midnight in every person",
        "D": "Only after eating"
      },
      "correctAnswer": "B",
      "explanation": "The lab describes a circadian cortisol rhythm that is high in the early morning and low near sleep.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The lab describes a circadian cortisol rhythm that is high in the early morning and low near sleep.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 18,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Cortisol Rhythm",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_019",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Cortisol Actions",
      "question": "Which action is associated with cortisol?",
      "choices": {
        "A": "Lowering protein and fat breakdown to zero",
        "B": "Producing thyroid hormone in the adrenal cortex",
        "C": "Supporting fuel availability during stress",
        "D": "Directly replacing aldosterone at the kidney"
      },
      "correctAnswer": "C",
      "explanation": "Cortisol helps the body adapt to stress partly by mobilizing fuel through protein and fat catabolism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol helps the body adapt to stress partly by mobilizing fuel through protein and fat catabolism.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 19,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Cortisol Actions",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_020",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Negative Feedback",
      "question": "What happens to CRH and ACTH when cortisol remains elevated?",
      "choices": {
        "A": "Both are stimulated",
        "B": "CRH rises while ACTH falls",
        "C": "CRH falls while ACTH rises",
        "D": "Both are suppressed"
      },
      "correctAnswer": "D",
      "explanation": "Cortisol normally restrains hypothalamic CRH and pituitary ACTH through negative feedback.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cortisol normally restrains hypothalamic CRH and pituitary ACTH through negative feedback.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 20,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Negative Feedback",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_021",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Adrenal Insufficiency",
      "question": "Low cortisol with high ACTH most strongly indicates failure at which level?",
      "choices": {
        "A": "Adrenal cortex",
        "B": "Anterior pituitary",
        "C": "Hypothalamus",
        "D": "Suprachiasmatic nucleus"
      },
      "correctAnswer": "A",
      "explanation": "When the adrenal cortex fails, low cortisol removes feedback and an intact pituitary raises ACTH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "When the adrenal cortex fails, low cortisol removes feedback and an intact pituitary raises ACTH.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 21,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Adrenal Insufficiency",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_022",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Adrenal Insufficiency",
      "question": "Low cortisol with low ACTH points most directly to dysfunction at which level?",
      "choices": {
        "A": "Adrenal cortex only",
        "B": "Pituitary or hypothalamus",
        "C": "Thyroid gland",
        "D": "Kidney juxtaglomerular cells"
      },
      "correctAnswer": "B",
      "explanation": "Low ACTH despite low cortisol indicates inadequate upstream stimulation rather than primary adrenal failure.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low ACTH despite low cortisol indicates inadequate upstream stimulation rather than primary adrenal failure.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 22,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Adrenal Insufficiency",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_023",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "POMC and Pigmentation",
      "question": "Why can primary adrenal insufficiency cause hyperpigmentation?",
      "choices": {
        "A": "Low cortisol directly deposits pigment in the skin",
        "B": "Low aldosterone converts potassium into melanin",
        "C": "High POMC production increases ACTH and MSH-related signaling",
        "D": "High renin activates thyroid pigment receptors"
      },
      "correctAnswer": "C",
      "explanation": "Loss of cortisol feedback raises POMC-derived ACTH; POMC also yields melanocyte-stimulating signals that darken the skin.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Loss of cortisol feedback raises POMC-derived ACTH; POMC also yields melanocyte-stimulating signals that darken the skin.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 23,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "POMC and Pigmentation",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_024",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Adrenal Insufficiency",
      "question": "Why may aldosterone be low in primary adrenal failure but remain normal in pituitary-related cortisol deficiency?",
      "choices": {
        "A": "Aldosterone depends entirely on ACTH in both conditions",
        "B": "The pituitary directly secretes aldosterone",
        "C": "Cortisol is converted to aldosterone in the kidney",
        "D": "RAAS controls aldosterone, but the adrenal cortex must be intact"
      },
      "correctAnswer": "D",
      "explanation": "Primary adrenal damage can reduce all cortical output, while an intact adrenal can maintain aldosterone through RAAS despite low ACTH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Primary adrenal damage can reduce all cortical output, while an intact adrenal can maintain aldosterone through RAAS despite low ACTH.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 24,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Adrenal Insufficiency",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_025",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Exogenous Steroid Suppression",
      "question": "What happens to endogenous CRH, ACTH, and cortisol during prolonged prednisone therapy?",
      "choices": {
        "A": "All are suppressed",
        "B": "All are increased",
        "C": "CRH increases while ACTH and cortisol fall",
        "D": "CRH and ACTH fall while endogenous cortisol rises"
      },
      "correctAnswer": "A",
      "explanation": "Exogenous glucocorticoid feedback suppresses CRH and ACTH, reducing the patient's own adrenal cortisol production.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Exogenous glucocorticoid feedback suppresses CRH and ACTH, reducing the patient's own adrenal cortisol production.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 25,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Exogenous Steroid Suppression",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_026",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "RAAS Sequence",
      "question": "Which sequence correctly follows the major RAAS steps?",
      "choices": {
        "A": "Angiotensin II -> renin -> angiotensin I -> aldosterone",
        "B": "Renin -> angiotensin I -> angiotensin II -> aldosterone",
        "C": "Aldosterone -> renin -> angiotensin I -> angiotensin II",
        "D": "Renin -> aldosterone -> angiotensin I -> angiotensin II"
      },
      "correctAnswer": "B",
      "explanation": "Renin initiates angiotensin I formation, ACE supports angiotensin II formation, and angiotensin II stimulates aldosterone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Renin initiates angiotensin I formation, ACE supports angiotensin II formation, and angiotensin II stimulates aldosterone.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 26,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "RAAS Sequence",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_027",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "Renin Source",
      "question": "Where is renin released?",
      "choices": {
        "A": "Zona glomerulosa of the adrenal cortex",
        "B": "Anterior pituitary corticotrophs",
        "C": "Juxtaglomerular cells of the kidney",
        "D": "Thyroid follicular cells"
      },
      "correctAnswer": "C",
      "explanation": "Kidney juxtaglomerular cells release renin when renal perfusion signals call for RAAS activation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Kidney juxtaglomerular cells release renin when renal perfusion signals call for RAAS activation.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 27,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "Renin Source",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_028",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "Aldosterone Source",
      "question": "Which adrenal-cortical zone produces aldosterone?",
      "choices": {
        "A": "Zona fasciculata",
        "B": "Zona reticularis",
        "C": "Adrenal medulla",
        "D": "Zona glomerulosa"
      },
      "correctAnswer": "D",
      "explanation": "The zona glomerulosa is the outer adrenal-cortical layer and the source of aldosterone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The zona glomerulosa is the outer adrenal-cortical layer and the source of aldosterone.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 28,
      "learningLevel": "Foundation",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "Aldosterone Source",
        "learning_level": "Foundation",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_029",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "Aldosterone Actions",
      "question": "How does aldosterone normally affect renal potassium handling?",
      "choices": {
        "A": "It increases potassium excretion",
        "B": "It increases potassium retention",
        "C": "It prevents sodium reabsorption",
        "D": "It blocks distal nephron transport"
      },
      "correctAnswer": "A",
      "explanation": "Aldosterone supports sodium reabsorption while promoting renal potassium secretion and excretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Aldosterone supports sodium reabsorption while promoting renal potassium secretion and excretion.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 29,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "Aldosterone Actions",
        "learning_level": "Applied Reinforcement",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_030",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "ACE Inhibition",
      "question": "Which pattern is expected after starting an ACE inhibitor?",
      "choices": {
        "A": "Angiotensin I falls, angiotensin II rises, and renin falls",
        "B": "Angiotensin I rises, angiotensin II falls, and renin rises",
        "C": "Both angiotensins rise while renin falls",
        "D": "Both angiotensins fall while aldosterone rises"
      },
      "correctAnswer": "B",
      "explanation": "Blocking ACE reduces angiotensin II, removes feedback restraint on renin, and allows angiotensin I to accumulate.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Blocking ACE reduces angiotensin II, removes feedback restraint on renin, and allows angiotensin I to accumulate.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 30,
      "learningLevel": "Integrative",
      "questionType": "Learn",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "ACE Inhibition",
        "learning_level": "Integrative",
        "question_type": "Learn"
      }
    },
    {
      "id": "LAB11_031",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Lesion Localization",
      "question": "A patient has TSH 8.2 (high), free T4 0.6 (low), and low oxygen consumption. Where is the most likely defect?",
      "choices": {
        "A": "Anterior pituitary",
        "B": "Hypothalamus",
        "C": "Thyroid gland",
        "D": "Adrenal cortex"
      },
      "correctAnswer": "C",
      "explanation": "High TSH with low free T4 shows that the pituitary is responding but the thyroid is failing to produce hormone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "High TSH with low free T4 shows that the pituitary is responding but the thyroid is failing to produce hormone.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 31,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Lesion Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_032",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Lesion Localization",
      "question": "A patient has low TSH, low free T4, and low oxygen consumption. Which location best explains the pattern?",
      "choices": {
        "A": "Thyroid gland",
        "B": "Adrenal medulla",
        "C": "Kidney",
        "D": "Anterior pituitary"
      },
      "correctAnswer": "D",
      "explanation": "Low TSH and low T4 indicate inadequate pituitary stimulation of the thyroid, producing secondary hypothyroidism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low TSH and low T4 indicate inadequate pituitary stimulation of the thyroid, producing secondary hypothyroidism.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 32,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Lesion Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_033",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Lesion Localization",
      "question": "A patient has high TSH, high free T4, and high oxygen consumption. Which explanation is supported by this pattern?",
      "choices": {
        "A": "A TSH-secreting pituitary adenoma",
        "B": "Complete thyroid removal",
        "C": "Exogenous cortisol use",
        "D": "Primary adrenal insufficiency"
      },
      "correctAnswer": "A",
      "explanation": "Autonomous pituitary TSH secretion can drive high thyroid hormone despite feedback that should normally suppress TSH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Autonomous pituitary TSH secretion can drive high thyroid hormone despite feedback that should normally suppress TSH.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 33,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Lesion Localization",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_034",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Thyroidectomy",
      "question": "Six weeks after total thyroidectomy without replacement, which paired change is expected?",
      "choices": {
        "A": "Free T4 rises while TSH becomes suppressed",
        "B": "Free T4 approaches zero while TSH becomes markedly elevated",
        "C": "Free T4 and TSH both remain at the surgical baseline",
        "D": "Free T4 rises because pituitary TSH replaces thyroid tissue"
      },
      "correctAnswer": "B",
      "explanation": "Loss of thyroid tissue lowers T4, and loss of feedback allows TSH to climb progressively.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Loss of thyroid tissue lowers T4, and loss of feedback allows TSH to climb progressively.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 34,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Thyroidectomy",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_035",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Radioiodine Uptake",
      "question": "Why is TSH intentionally allowed to rise before a scan for residual thyroid tissue?",
      "choices": {
        "A": "High TSH prevents all thyroid cells from taking up iodine",
        "B": "High TSH converts radioiodine into T4 in the pituitary",
        "C": "High TSH maximizes iodine uptake by remaining thyroid cells",
        "D": "High TSH suppresses metastatic thyroid tissue"
      },
      "correctAnswer": "C",
      "explanation": "Elevated TSH strongly stimulates any residual thyroid tissue, improving its radioiodine uptake and detectability.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Elevated TSH strongly stimulates any residual thyroid tissue, improving its radioiodine uptake and detectability.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 35,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Radioiodine Uptake",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_036",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Exogenous Hormone and RAIU",
      "question": "A patient taking levothyroxine for weight loss has high T4, low TSH, and low diffuse RAIU. Why is uptake low?",
      "choices": {
        "A": "Exogenous T4 directly destroys the thyroid gland",
        "B": "Low TSH increases iodine trapping in thyroid cells",
        "C": "High T4 stimulates TSH-receptor antibodies",
        "D": "Exogenous T4 suppresses TSH-driven thyroid iodine uptake"
      },
      "correctAnswer": "D",
      "explanation": "The external hormone suppresses TSH, leaving the patient's thyroid relatively inactive and poorly stimulated to take up iodine.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The external hormone suppresses TSH, leaving the patient's thyroid relatively inactive and poorly stimulated to take up iodine.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 36,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Exogenous Hormone and RAIU",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_037",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Axis Recovery",
      "question": "Why might a patient briefly feel hypothyroid after stopping unnecessary levothyroxine?",
      "choices": {
        "A": "TSH and thyroid output need time to recover from suppression",
        "B": "The thyroid permanently loses all TSH receptors",
        "C": "Free T4 immediately falls while TSH remains permanently zero",
        "D": "The adrenal cortex must first produce replacement T4"
      },
      "correctAnswer": "A",
      "explanation": "As exogenous T4 falls, pituitary and thyroid activity may recover more slowly, creating a temporary period of low endogenous output.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "As exogenous T4 falls, pituitary and thyroid activity may recover more slowly, creating a temporary period of low endogenous output.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 37,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Axis Recovery",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_038",
      "unit": "lab-11",
      "conceptBlock": "HPT Axis",
      "subtopic": "Graves Disease",
      "question": "Which combination best distinguishes Graves disease from exogenous levothyroxine use?",
      "choices": {
        "A": "Absent receptor stimulation with low diffuse RAIU",
        "B": "TSH-receptor stimulation with high diffuse RAIU",
        "C": "High TSH with absent thyroid-hormone production",
        "D": "Low T4 with progressively rising TSH"
      },
      "correctAnswer": "B",
      "explanation": "Graves antibodies stimulate the TSH receptor and active iodine uptake, unlike an externally supplied hormone that suppresses the gland.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Graves antibodies stimulate the TSH receptor and active iodine uptake, unlike an externally supplied hormone that suppresses the gland.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 38,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPT Axis",
        "concept_group": "Graves Disease",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_039",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Adrenal Insufficiency",
      "question": "A patient has low morning cortisol, high ACTH, hypotension, and diffuse hyperpigmentation. What is the best localization?",
      "choices": {
        "A": "Pituitary ACTH deficiency",
        "B": "Hypothalamic CRH deficiency",
        "C": "Primary adrenal cortex failure",
        "D": "Autonomous adrenal cortisol secretion"
      },
      "correctAnswer": "C",
      "explanation": "Low cortisol with compensatory high ACTH and pigmentation localizes the defect to the adrenal cortex.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low cortisol with compensatory high ACTH and pigmentation localizes the defect to the adrenal cortex.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 39,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Adrenal Insufficiency",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_040",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Adrenal Insufficiency",
      "question": "Low morning cortisol, low ACTH, and no pigment change most strongly suggest which problem?",
      "choices": {
        "A": "Primary adrenal destruction",
        "B": "Autonomous cortisol secretion",
        "C": "Primary hyperaldosteronism",
        "D": "Reduced pituitary or hypothalamic drive"
      },
      "correctAnswer": "D",
      "explanation": "Low ACTH despite low cortisol indicates an upstream defect, and the absence of ACTH excess explains the lack of pigmentation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low ACTH despite low cortisol indicates an upstream defect, and the absence of ACTH excess explains the lack of pigmentation.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 40,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Adrenal Insufficiency",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_041",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "POMC and Pigmentation",
      "question": "Which change most directly connects high ACTH to hyperpigmentation?",
      "choices": {
        "A": "More POMC-derived melanocyte stimulation",
        "B": "Increased conversion of cortisol to melanin",
        "C": "Reduced aldosterone binding in skin",
        "D": "Increased thyroid peroxidase activity"
      },
      "correctAnswer": "A",
      "explanation": "ACTH and melanocyte-stimulating signals share the POMC precursor, so strong POMC production can increase pigmentation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "ACTH and melanocyte-stimulating signals share the POMC precursor, so strong POMC production can increase pigmentation.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 41,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "POMC and Pigmentation",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_042",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Cortisol and Aldosterone",
      "question": "Two patients have low cortisol. Why is aldosterone more likely to remain normal in the patient with low ACTH?",
      "choices": {
        "A": "Low ACTH directly increases aldosterone release",
        "B": "An intact adrenal cortex still responds to RAAS",
        "C": "The pituitary begins secreting aldosterone",
        "D": "Cortisol deficiency is converted into aldosterone"
      },
      "correctAnswer": "B",
      "explanation": "An upstream ACTH defect reduces cortisol, but an intact zona glomerulosa can still respond to RAAS.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "An upstream ACTH defect reduces cortisol, but an intact zona glomerulosa can still respond to RAAS.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 42,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Cortisol and Aldosterone",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_043",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Contralateral Adrenal Suppression",
      "question": "Before removal of a cortisol-secreting adrenal adenoma, what happens to the opposite adrenal gland?",
      "choices": {
        "A": "High ACTH causes it to enlarge and overproduce cortisol",
        "B": "High renin converts it into thyroid tissue",
        "C": "Low ACTH causes it to become suppressed and atrophic",
        "D": "Low cortisol causes it to release excess aldosterone"
      },
      "correctAnswer": "C",
      "explanation": "Tumor-derived cortisol suppresses CRH and ACTH, so the non-tumor adrenal receives little stimulation and atrophies.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Tumor-derived cortisol suppresses CRH and ACTH, so the non-tumor adrenal receives little stimulation and atrophies.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 43,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Contralateral Adrenal Suppression",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_044",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Postoperative Adrenal Insufficiency",
      "question": "Immediately after the cortisol-secreting gland is removed, why can the remaining adrenal fail to maintain cortisol?",
      "choices": {
        "A": "It has been overstimulated by high ACTH",
        "B": "It cannot receive blood after unilateral surgery",
        "C": "It produces only thyroid hormone",
        "D": "It has been chronically suppressed by low ACTH"
      },
      "correctAnswer": "D",
      "explanation": "The remaining gland is anatomically present but functionally suppressed and cannot immediately replace the removed cortisol source.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The remaining gland is anatomically present but functionally suppressed and cannot immediately replace the removed cortisol source.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 44,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Postoperative Adrenal Insufficiency",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_045",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Postoperative Steroid Coverage",
      "question": "Why is perioperative glucocorticoid coverage needed after removing a cortisol-secreting adrenal tumor?",
      "choices": {
        "A": "The tumor is removed while the other gland remains suppressed",
        "B": "The remaining adrenal immediately overproduces cortisol",
        "C": "Glucocorticoids are required to stimulate thyroid iodine uptake",
        "D": "Surgery permanently eliminates pituitary ACTH"
      },
      "correctAnswer": "A",
      "explanation": "Removal eliminates the autonomous source while the contralateral gland remains suppressed, creating an acute cortisol-deficiency risk.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Removal eliminates the autonomous source while the contralateral gland remains suppressed, creating an acute cortisol-deficiency risk.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 45,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Postoperative Steroid Coverage",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_046",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Axis Recovery",
      "question": "Why should glucocorticoid coverage be tapered slowly after chronic HPA suppression?",
      "choices": {
        "A": "A rapid taper causes permanent ACTH excess in every patient",
        "B": "The entire HPA axis needs time to recover",
        "C": "The thyroid must first convert cortisol to T3",
        "D": "Aldosterone cannot be produced during any taper"
      },
      "correctAnswer": "B",
      "explanation": "Recovery of CRH, ACTH, and adrenal responsiveness can take months, so gradual reduction prevents an abrupt support gap.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Recovery of CRH, ACTH, and adrenal responsiveness can take months, so gradual reduction prevents an abrupt support gap.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 46,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Axis Recovery",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_047",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Exogenous Steroid Withdrawal",
      "question": "A patient abruptly stops prednisone after four months. Which immediate pattern is most likely?",
      "choices": {
        "A": "High ACTH with immediate cortisol excess",
        "B": "Normal cortisol because the adrenal never responds to ACTH",
        "C": "Low exogenous support with persistently low endogenous cortisol",
        "D": "High CRH with instant adrenal recovery"
      },
      "correctAnswer": "C",
      "explanation": "Chronic prednisone suppresses the axis; abrupt withdrawal removes external support before endogenous cortisol production has recovered.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chronic prednisone suppresses the axis; abrupt withdrawal removes external support before endogenous cortisol production has recovered.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 47,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Exogenous Steroid Withdrawal",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_048",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Cushing Localization",
      "question": "A patient has cortisol excess with suppressed ACTH. Which source is most likely?",
      "choices": {
        "A": "Pituitary ACTH secretion",
        "B": "Ectopic ACTH secretion",
        "C": "Hypothalamic CRH stimulation",
        "D": "An adrenal cortisol-secreting tumor"
      },
      "correctAnswer": "D",
      "explanation": "An adrenal cortisol source suppresses normal CRH and ACTH through feedback, making low ACTH the key localizing clue.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "An adrenal cortisol source suppresses normal CRH and ACTH through feedback, making low ACTH the key localizing clue.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 48,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Cushing Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_049",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Cushing Localization",
      "question": "Cortisol excess with high-normal or mildly elevated ACTH and a pituitary lesion best fits which cause?",
      "choices": {
        "A": "Pituitary ACTH overproduction",
        "B": "Autonomous adrenal cortisol secretion",
        "C": "Abrupt glucocorticoid withdrawal",
        "D": "Primary adrenal failure"
      },
      "correctAnswer": "A",
      "explanation": "A pituitary ACTH source drives the adrenal cortex and produces Cushing disease.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "A pituitary ACTH source drives the adrenal cortex and produces Cushing disease.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 49,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Cushing Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_050",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Cushing Localization",
      "question": "Very high ACTH with cortisol excess and no pituitary abnormality raises concern for which source?",
      "choices": {
        "A": "Autonomous adrenal aldosterone production",
        "B": "Ectopic ACTH production",
        "C": "Thyroid-hormone resistance",
        "D": "Primary cortisol deficiency"
      },
      "correctAnswer": "B",
      "explanation": "An ACTH-secreting source outside the pituitary can strongly stimulate adrenal cortisol while bypassing normal axis control.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "An ACTH-secreting source outside the pituitary can strongly stimulate adrenal cortisol while bypassing normal axis control.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 50,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Cushing Localization",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_051",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Iatrogenic Cortisol Excess",
      "question": "Long-term high-dose corticosteroid exposure produces Cushing features through which mechanism?",
      "choices": {
        "A": "Primary adrenal cortisol deficiency",
        "B": "Pituitary failure to release ACTH",
        "C": "Exogenous glucocorticoid excess",
        "D": "Kidney failure to release renin"
      },
      "correctAnswer": "C",
      "explanation": "Medication can create prolonged glucocorticoid exposure and the clinical pattern of iatrogenic Cushing syndrome.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Medication can create prolonged glucocorticoid exposure and the clinical pattern of iatrogenic Cushing syndrome.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 51,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Iatrogenic Cortisol Excess",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_052",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Bilateral Adrenalectomy",
      "question": "Which lifelong replacements are essential after both adrenal glands are removed?",
      "choices": {
        "A": "ACTH and CRH",
        "B": "Epinephrine and norepinephrine only",
        "C": "Thyroid hormone and TSH",
        "D": "Cortisol and aldosterone"
      },
      "correctAnswer": "D",
      "explanation": "Bilateral adrenalectomy removes cortisol and aldosterone sources, so both glucocorticoid and mineralocorticoid replacement are required.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Bilateral adrenalectomy removes cortisol and aldosterone sources, so both glucocorticoid and mineralocorticoid replacement are required.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 52,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Bilateral Adrenalectomy",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_053",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Mineralocorticoid Replacement",
      "question": "What is the major danger of omitting mineralocorticoid replacement after bilateral adrenalectomy?",
      "choices": {
        "A": "Hyperkalemia, sodium loss, and severe hypotension",
        "B": "Hypokalemia, sodium retention, and hypertension",
        "C": "High T4, low TSH, and heat intolerance",
        "D": "High cortisol, central obesity, and striae"
      },
      "correctAnswer": "A",
      "explanation": "Without aldosterone action, the kidney loses sodium and retains potassium, causing volume depletion, hypotension, and dangerous hyperkalemia.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Without aldosterone action, the kidney loses sodium and retains potassium, causing volume depletion, hypotension, and dangerous hyperkalemia.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 53,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Mineralocorticoid Replacement",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_054",
      "unit": "lab-11",
      "conceptBlock": "HPA Axis",
      "subtopic": "Loss of Cortisol Feedback",
      "question": "Why can a pituitary corticotroph tumor enlarge after bilateral adrenalectomy?",
      "choices": {
        "A": "Loss of aldosterone directly raises TSH",
        "B": "Loss of cortisol feedback removes restraint",
        "C": "Adrenal removal increases thyroid iodine uptake",
        "D": "Low potassium suppresses all pituitary growth"
      },
      "correctAnswer": "B",
      "explanation": "With no adrenal cortisol, pituitary corticotrophs lose feedback inhibition and may increase ACTH/POMC activity and tumor growth.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "With no adrenal cortisol, pituitary corticotrophs lose feedback inhibition and may increase ACTH/POMC activity and tumor growth.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 54,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "HPA Axis",
        "concept_group": "Loss of Cortisol Feedback",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_055",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "Primary Hyperaldosteronism",
      "question": "A hypertensive patient has high aldosterone and suppressed renin. Which cause best fits?",
      "choices": {
        "A": "Renal artery stenosis",
        "B": "ACE inhibition",
        "C": "An aldosterone-producing tumor",
        "D": "Primary adrenal aldosterone failure"
      },
      "correctAnswer": "C",
      "explanation": "An adrenal adenoma can secrete aldosterone independently; volume expansion then suppresses kidney renin release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "An adrenal adenoma can secrete aldosterone independently; volume expansion then suppresses kidney renin release.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 55,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "Primary Hyperaldosteronism",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_056",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "Secondary Hyperaldosteronism",
      "question": "High aldosterone with high renin in a hypertensive patient most strongly supports which cause?",
      "choices": {
        "A": "Conn syndrome",
        "B": "Bilateral adrenalectomy",
        "C": "Exogenous cortisol use",
        "D": "Renal artery stenosis"
      },
      "correctAnswer": "D",
      "explanation": "Reduced renal perfusion drives renin, angiotensin II, and secondary aldosterone secretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Reduced renal perfusion drives renin, angiotensin II, and secondary aldosterone secretion.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 56,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "Secondary Hyperaldosteronism",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_057",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "Renal Artery Stenosis",
      "question": "Which sequence connects renal artery narrowing to high aldosterone?",
      "choices": {
        "A": "Reduced renal perfusion -> renin -> angiotensin II -> aldosterone",
        "B": "Reduced renal perfusion -> low renin -> low angiotensin II -> aldosterone",
        "C": "High aldosterone -> renal narrowing -> low renin -> cortisol",
        "D": "Renal narrowing -> ACTH -> cortisol -> aldosterone"
      },
      "correctAnswer": "A",
      "explanation": "The kidney senses reduced perfusion and activates renin, leading to angiotensin II and adrenal aldosterone release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The kidney senses reduced perfusion and activates renin, leading to angiotensin II and adrenal aldosterone release.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 57,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "Renal Artery Stenosis",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_058",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "ACE Inhibition",
      "question": "Two weeks after starting lisinopril, which complete pattern is expected?",
      "choices": {
        "A": "Low renin, low angiotensin I, high angiotensin II, and high aldosterone",
        "B": "High renin, high angiotensin I, low angiotensin II, and low aldosterone",
        "C": "High renin, low angiotensin I, high angiotensin II, and high aldosterone",
        "D": "Low renin, high angiotensin I, low angiotensin II, and high aldosterone"
      },
      "correctAnswer": "B",
      "explanation": "ACE blockade lowers angiotensin II and aldosterone while reduced feedback raises renin and allows angiotensin I to increase.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "ACE blockade lowers angiotensin II and aldosterone while reduced feedback raises renin and allows angiotensin I to increase.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 58,
      "learningLevel": "Integrative",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "ACE Inhibition",
        "learning_level": "Integrative",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_059",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "ARB Comparison",
      "question": "How do angiotensin II levels usually differ with an ARB compared with an ACE inhibitor?",
      "choices": {
        "A": "They must fall to zero with an ARB",
        "B": "They become aldosterone with an ARB",
        "C": "They may remain normal or rise with an ARB",
        "D": "They are unaffected by either drug"
      },
      "correctAnswer": "C",
      "explanation": "An ARB blocks the angiotensin II receptor rather than its formation, so circulating angiotensin II may persist or increase.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "An ARB blocks the angiotensin II receptor rather than its formation, so circulating angiotensin II may persist or increase.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 59,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "ARB Comparison",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    },
    {
      "id": "LAB11_060",
      "unit": "lab-11",
      "conceptBlock": "RAAS and Aldosterone",
      "subtopic": "ACE and Bradykinin",
      "question": "Why can an ACE inhibitor cause a dry cough while an ARB usually does not?",
      "choices": {
        "A": "ARB therapy increases bradykinin production",
        "B": "ACE inhibition directly stimulates TSH",
        "C": "ARB therapy prevents all renin release",
        "D": "ACE inhibition allows bradykinin to accumulate"
      },
      "correctAnswer": "D",
      "explanation": "ACE normally degrades bradykinin; blocking ACE can increase bradykinin, whereas receptor blockade occurs downstream and does not impair its breakdown.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "ACE normally degrades bradykinin; blocking ACE can increase bradykinin, whereas receptor blockade occurs downstream and does not impair its breakdown.",
      "bankId": "lab11_thyroid_adrenal_sprint_v2_3",
      "bankType": "sprint",
      "contentGroup": "labs",
      "sessionMode": "labs",
      "sourceLecture": "Lab 11 - Thyroid and Adrenal Hormones",
      "sourceOrder": 60,
      "learningLevel": "Applied Reinforcement",
      "questionType": "Mixed Review",
      "metadata": {
        "source": "Lab 11 - Thyroid and Adrenal Hormones",
        "broad_category": "RAAS and Aldosterone",
        "concept_group": "ACE and Bradykinin",
        "learning_level": "Applied Reinforcement",
        "question_type": "Mixed Review"
      }
    }
  ]
};
window.LAB11_SPRINT_QUESTIONS = window.LAB11_SPRINT_BANK.questions;
