window.PITUITARY_SPRINT_BANK = {
  "schemaVersion": "1.0.0",
  "bankId": "pituitary_sprint_v2_2",
  "bankType": "sprint",
  "mode": "learn",
  "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
  "questionCount": 46,
  "questions": [
    {
      "id": "PIT_SPRINT_001",
      "unit": "pituitary",
      "conceptBlock": "Hypothalamic-Pituitary Organization",
      "subtopic": "Hypothalamic Roles",
      "question": "Why is the hypothalamus described as a master gland in this lecture?",
      "choices": {
        "A": "It produces every circulating hormone",
        "B": "It controls the pituitary through neural and hormonal mechanisms",
        "C": "It stores all anterior pituitary hormones",
        "D": "It replaces the regulatory functions of target glands"
      },
      "correctAnswer": "B",
      "explanation": "The hypothalamus coordinates pituitary activity through neural pathways and tropic hormones, linking nervous-system signals to endocrine control.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The hypothalamus coordinates pituitary activity through neural pathways and tropic hormones, linking nervous-system signals to endocrine control.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 1,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Hypothalamic-Pituitary Organization",
        "concept_group": "Hypothalamic Roles",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_002",
      "unit": "pituitary",
      "conceptBlock": "Hypothalamic-Pituitary Organization",
      "subtopic": "Hypothalamic Roles",
      "question": "If body-fluid concentration changes, what hypothalamic function responds most directly?",
      "choices": {
        "A": "Regulation of body rhythms",
        "B": "Coordination of defensive reactions",
        "C": "Regulation of appetite behavior",
        "D": "Regulation of osmolarity"
      },
      "correctAnswer": "D",
      "explanation": "Hypothalamic osmoregulatory mechanisms detect changes in body-fluid concentration and help coordinate an appropriate hormonal response.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Hypothalamic osmoregulatory mechanisms detect changes in body-fluid concentration and help coordinate an appropriate hormonal response.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 2,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Hypothalamic-Pituitary Organization",
        "concept_group": "Hypothalamic Roles",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_003",
      "unit": "pituitary",
      "conceptBlock": "Hypothalamic-Pituitary Organization",
      "subtopic": "Pituitary Anatomy and Origins",
      "question": "Where is the pituitary gland located?",
      "choices": {
        "A": "In the sella turcica of the sphenoid bone",
        "B": "In the median eminence of the hypothalamus",
        "C": "In the zona fasciculata of the adrenal cortex",
        "D": "In the epiphyseal cartilage of long bones"
      },
      "correctAnswer": "A",
      "explanation": "The pituitary lies within the sella turcica and connects to the hypothalamus through the hypophysial stalk.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The pituitary lies within the sella turcica and connects to the hypothalamus through the hypophysial stalk.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 3,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Hypothalamic-Pituitary Organization",
        "concept_group": "Pituitary Anatomy and Origins",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_004",
      "unit": "pituitary",
      "conceptBlock": "Hypothalamic-Pituitary Organization",
      "subtopic": "Pituitary Anatomy and Origins",
      "question": "How do the tissue origins of the two pituitary lobes differ?",
      "choices": {
        "A": "Both lobes arise from Rathke's pouch",
        "B": "Both lobes arise from neural tissue",
        "C": "The anterior lobe arises from Rathke's pouch, while the posterior lobe has neural origins",
        "D": "The anterior lobe has neural origins, while the posterior lobe arises from Rathke's pouch"
      },
      "correctAnswer": "C",
      "explanation": "The adenohypophysis develops from Rathke's pouch, whereas the neurohypophysis arises from neural tissue connected to the hypothalamus.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The adenohypophysis develops from Rathke's pouch, whereas the neurohypophysis arises from neural tissue connected to the hypothalamus.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 4,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Hypothalamic-Pituitary Organization",
        "concept_group": "Pituitary Anatomy and Origins",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_005",
      "unit": "pituitary",
      "conceptBlock": "Hypothalamic-Pituitary Organization",
      "subtopic": "Hypophyseal Portal System",
      "question": "What is a major advantage of the hypophyseal portal system?",
      "choices": {
        "A": "It stores posterior pituitary hormones in systemic veins",
        "B": "It delivers hypothalamic hormones without first diluting them in systemic blood",
        "C": "It carries anterior pituitary hormones directly to the hypothalamus",
        "D": "It allows target-gland hormones to bypass the anterior pituitary"
      },
      "correctAnswer": "B",
      "explanation": "Portal vessels carry releasing and inhibiting hormones directly from the hypothalamic region to the anterior pituitary at effective concentrations.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Portal vessels carry releasing and inhibiting hormones directly from the hypothalamic region to the anterior pituitary at effective concentrations.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 5,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Hypothalamic-Pituitary Organization",
        "concept_group": "Hypophyseal Portal System",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_006",
      "unit": "pituitary",
      "conceptBlock": "Hypothalamic-Pituitary Organization",
      "subtopic": "Hypophyseal Portal System",
      "question": "Following release into hypothalamic vessels, how do releasing hormones reach the anterior pituitary?",
      "choices": {
        "A": "Hypothalamic vessels to hypophyseal portal veins to the anterior pituitary",
        "B": "Hypothalamic axons to systemic veins to the anterior pituitary",
        "C": "Anterior pituitary vessels to the pituitary stalk to the hypothalamus",
        "D": "Posterior pituitary axons to portal veins to the anterior pituitary"
      },
      "correctAnswer": "A",
      "explanation": "Vessels merge into hypophyseal portal veins that descend along the stalk and deliver hypothalamic hormones to the adenohypophysis.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Vessels merge into hypophyseal portal veins that descend along the stalk and deliver hypothalamic hormones to the adenohypophysis.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 6,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Hypothalamic-Pituitary Organization",
        "concept_group": "Hypophyseal Portal System",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_007",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Hypothalamic Control",
      "question": "A decrease in FSH and LH could result directly from loss of which hypothalamic signal?",
      "choices": {
        "A": "Corticotropin-releasing hormone",
        "B": "Growth hormone-releasing hormone",
        "C": "Thyrotropin-releasing hormone",
        "D": "Gonadotropin-releasing hormone"
      },
      "correctAnswer": "D",
      "explanation": "GnRH stimulates gonadotrophs to release FSH and LH; CRH, TRH, and GHRH regulate different anterior pituitary hormones.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GnRH stimulates gonadotrophs to release FSH and LH; CRH, TRH, and GHRH regulate different anterior pituitary hormones.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 7,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Hypothalamic Control",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_008",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Hypothalamic Control",
      "question": "An increase in circulating glucocorticoids would most directly reduce stimulation of which anterior pituitary hormone?",
      "choices": {
        "A": "Prolactin",
        "B": "Adrenocorticotropic hormone",
        "C": "Follicle-stimulating hormone",
        "D": "Thyroid-stimulating hormone"
      },
      "correctAnswer": "B",
      "explanation": "Glucocorticoid levels influence CRH-driven control of ACTH, providing feedback within the hypothalamic-pituitary-adrenal relationship.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Glucocorticoid levels influence CRH-driven control of ACTH, providing feedback within the hypothalamic-pituitary-adrenal relationship.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 8,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Hypothalamic Control",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_009",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Anterior Pituitary Cells and Targets",
      "question": "Production of thyroid-stimulating hormone identifies an anterior pituitary cell as a member of which cell type?",
      "choices": {
        "A": "Corticotropes",
        "B": "Gonadotrophs",
        "C": "Thyrotropes",
        "D": "Lactotrophs"
      },
      "correctAnswer": "C",
      "explanation": "Thyrotropes produce TSH, whereas corticotropes produce ACTH and the other listed cell types secrete different pituitary hormones.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyrotropes produce TSH, whereas corticotropes produce ACTH and the other listed cell types secrete different pituitary hormones.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 9,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Anterior Pituitary Cells and Targets",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_010",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Anterior Pituitary Cells and Targets",
      "question": "Following ACTH release, where does it act within the adrenal gland according to the lecture?",
      "choices": {
        "A": "Zona fasciculata",
        "B": "Adrenal medulla",
        "C": "Zona glomerulosa",
        "D": "Adrenal capsule"
      },
      "correctAnswer": "A",
      "explanation": "ACTH targets the zona fasciculata and controls hormone secretion from the adrenal cortex.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "ACTH targets the zona fasciculata and controls hormone secretion from the adrenal cortex.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 10,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Anterior Pituitary Cells and Targets",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_011",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Anterior Pituitary Cells and Targets",
      "question": "Production of growth hormone identifies an anterior pituitary cell as which type?",
      "choices": {
        "A": "Thyrotropes",
        "B": "Somatotropes",
        "C": "Corticotropes",
        "D": "Gonadotrophs"
      },
      "correctAnswer": "B",
      "explanation": "Somatotropes produce growth hormone, whereas lactotrophs produce prolactin and thyrotropes and corticotropes supply other endocrine axes.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Somatotropes produce growth hormone, whereas lactotrophs produce prolactin and thyrotropes and corticotropes supply other endocrine axes.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 11,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Anterior Pituitary Cells and Targets",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_012",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Gonadotropins and Prolactin",
      "question": "Damage to anterior pituitary lactotrophs would most directly reduce which hormone?",
      "choices": {
        "A": "Luteinizing hormone",
        "B": "Growth hormone",
        "C": "Thyroid-stimulating hormone",
        "D": "Prolactin"
      },
      "correctAnswer": "D",
      "explanation": "Lactotrophs produce prolactin, which supports mammary-gland development and milk production.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Lactotrophs produce prolactin, which supports mammary-gland development and milk production.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 12,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Gonadotropins and Prolactin",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_013",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Gonadotropins and Prolactin",
      "question": "What is a major effect of FSH in females?",
      "choices": {
        "A": "Stimulation of uterine contraction",
        "B": "Stimulation of testosterone secretion",
        "C": "Maturation of the ovarian follicle and ovum",
        "D": "Maturation of sperm in the testes"
      },
      "correctAnswer": "C",
      "explanation": "Female FSH promotes follicle and ovum maturation, while ovulation and testosterone secretion are associated with LH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Female FSH promotes follicle and ovum maturation, while ovulation and testosterone secretion are associated with LH.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 13,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Gonadotropins and Prolactin",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_014",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Gonadotropins and Prolactin",
      "question": "In a male, an increase in LH is expected to promote which response?",
      "choices": {
        "A": "Maturation of sperm",
        "B": "Secretion of testosterone",
        "C": "Maturation of an ovarian follicle",
        "D": "Production of milk"
      },
      "correctAnswer": "B",
      "explanation": "Male LH, also called ICSH, stimulates testosterone secretion, whereas FSH supports sperm maturation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Male LH, also called ICSH, stimulates testosterone secretion, whereas FSH supports sperm maturation.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 14,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Gonadotropins and Prolactin",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_015",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Hypothalamic Control",
      "question": "Prolactin secretion would rise if inhibition by which hypothalamic signal were reduced?",
      "choices": {
        "A": "Dopamine",
        "B": "Ghrelin",
        "C": "Somatostatin",
        "D": "Gonadotropin-releasing hormone"
      },
      "correctAnswer": "A",
      "explanation": "Dopamine restrains prolactin release as prolactin-inhibiting hormone; somatostatin instead inhibits growth hormone.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Dopamine restrains prolactin release as prolactin-inhibiting hormone; somatostatin instead inhibits growth hormone.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 15,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Hypothalamic Control",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_016",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Hypothalamic Control",
      "question": "An increase in TRH would most directly increase secretion of which hormone?",
      "choices": {
        "A": "Adrenocorticotropic hormone",
        "B": "Follicle-stimulating hormone",
        "C": "Growth hormone",
        "D": "Thyroid-stimulating hormone"
      },
      "correctAnswer": "D",
      "explanation": "TRH stimulates thyrotropes to release TSH, which then controls thyroid-gland hormone secretion.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "TRH stimulates thyrotropes to release TSH, which then controls thyroid-gland hormone secretion.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 16,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Hypothalamic Control",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_017",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Anterior Pituitary Cells and Targets",
      "question": "Production of ACTH identifies an anterior pituitary cell as which type?",
      "choices": {
        "A": "Gonadotrophs",
        "B": "Lactotrophs",
        "C": "Corticotropes",
        "D": "Somatotropes"
      },
      "correctAnswer": "C",
      "explanation": "Corticotropes produce ACTH in response to hypothalamic CRH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Corticotropes produce ACTH in response to hypothalamic CRH.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 17,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Anterior Pituitary Cells and Targets",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_018",
      "unit": "pituitary",
      "conceptBlock": "Anterior Pituitary Hormones",
      "subtopic": "Anterior Pituitary Cells and Targets",
      "question": "After a gonadotroph is activated, what pair of hormones can it release?",
      "choices": {
        "A": "FSH and LH",
        "B": "TSH and ACTH",
        "C": "GH and prolactin",
        "D": "ADH and oxytocin"
      },
      "correctAnswer": "A",
      "explanation": "Gonadotrophs secrete FSH and LH, whose reproductive effects depend on sex.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Gonadotrophs secrete FSH and LH, whose reproductive effects depend on sex.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 18,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Anterior Pituitary Hormones",
        "concept_group": "Anterior Pituitary Cells and Targets",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_019",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Actions and Regulation",
      "question": "Through which mediators does growth hormone produce many of its indirect effects?",
      "choices": {
        "A": "Gonadotropins",
        "B": "Growth hormone-releasing hormone",
        "C": "Somatostatin",
        "D": "Somatomedins"
      },
      "correctAnswer": "D",
      "explanation": "Somatomedins mediate many indirect GH effects; GHRH and somatostatin regulate GH secretion rather than carrying out those downstream actions.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Somatomedins mediate many indirect GH effects; GHRH and somatostatin regulate GH secretion rather than carrying out those downstream actions.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 19,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Actions and Regulation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_020",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Actions and Regulation",
      "question": "Growth hormone secretion increases after stimulation by which hypothalamic hormone?",
      "choices": {
        "A": "Somatostatin",
        "B": "Growth hormone-releasing hormone",
        "C": "Prolactin-inhibiting hormone",
        "D": "Corticotropin-releasing hormone"
      },
      "correctAnswer": "B",
      "explanation": "GHRH stimulates GH secretion, while growth hormone-inhibitory hormone, or somatostatin, suppresses it.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GHRH stimulates GH secretion, while growth hormone-inhibitory hormone, or somatostatin, suppresses it.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 20,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Actions and Regulation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_021",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Actions and Regulation",
      "question": "An increase in which variable tends to inhibit growth hormone secretion?",
      "choices": {
        "A": "Decreased blood glucose",
        "B": "Increased blood amino acids",
        "C": "Increased blood glucose",
        "D": "Decreased blood free fatty acids"
      },
      "correctAnswer": "C",
      "explanation": "Increased blood glucose inhibits GH secretion, whereas decreased glucose is listed as a stimulatory condition.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Increased blood glucose inhibits GH secretion, whereas decreased glucose is listed as a stimulatory condition.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 21,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Actions and Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_022",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Actions and Regulation",
      "question": "How does fasting generally affect growth hormone secretion?",
      "choices": {
        "A": "It increases secretion",
        "B": "It decreases secretion",
        "C": "It leaves secretion unchanged",
        "D": "It increases secretion only when blood glucose is high"
      },
      "correctAnswer": "A",
      "explanation": "Starvation or fasting is listed among the conditions that stimulate GH secretion, along with exercise, stress, and deep sleep.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Starvation or fasting is listed among the conditions that stimulate GH secretion, along with exercise, stress, and deep sleep.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 22,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Actions and Regulation",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_023",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Metabolic Effects",
      "question": "During increased growth hormone activity, what cellular change supports protein deposition?",
      "choices": {
        "A": "Reduced amino acid transport into cells",
        "B": "Reduced translation by ribosomes",
        "C": "Increased protein catabolism",
        "D": "Increased amino acid transport into cells"
      },
      "correctAnswer": "D",
      "explanation": "GH enhances amino acid transport, RNA translation, and transcription while decreasing protein and amino acid catabolism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH enhances amino acid transport, RNA translation, and transcription while decreasing protein and amino acid catabolism.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 23,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_024",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Metabolic Effects",
      "question": "During growth hormone action on adipose tissue, what change is expected?",
      "choices": {
        "A": "Decreased fatty acid release",
        "B": "Increased lipolysis",
        "C": "Increased glucose uptake",
        "D": "Decreased fat use for energy"
      },
      "correctAnswer": "B",
      "explanation": "GH promotes release of fat from adipose tissue and favors its use as an energy source.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH promotes release of fat from adipose tissue and favors its use as an energy source.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 24,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Metabolic Effects",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_025",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Metabolic Effects",
      "question": "How does growth hormone affect glucose uptake in skeletal muscle and adipose tissue?",
      "choices": {
        "A": "It decreases glucose uptake",
        "B": "It accelerates glucose uptake",
        "C": "It reverses glucose uptake",
        "D": "It leaves glucose uptake unchanged"
      },
      "correctAnswer": "A",
      "explanation": "GH reduces glucose uptake in skeletal muscle and fat, contributing to decreased carbohydrate use.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH reduces glucose uptake in skeletal muscle and fat, contributing to decreased carbohydrate use.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 25,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_026",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Metabolic Effects",
      "question": "Following an increase in growth hormone, what hepatic response is expected?",
      "choices": {
        "A": "Decreased gluconeogenesis",
        "B": "Increased glucose uptake",
        "C": "Increased glucose production",
        "D": "Decreased protein synthesis"
      },
      "correctAnswer": "C",
      "explanation": "GH increases hepatic glucose production; increased peripheral glucose uptake would oppose the lecture's described carbohydrate-sparing pattern.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH increases hepatic glucose production; increased peripheral glucose uptake would oppose the lecture's described carbohydrate-sparing pattern.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 26,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_027",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Metabolic Effects",
      "question": "Excessive growth hormone can contribute to which metabolic outcome?",
      "choices": {
        "A": "Increased glucose uptake by fat",
        "B": "Decreased hepatic glucose production",
        "C": "Reduced insulin secretion",
        "D": "Growth hormone-induced insulin resistance"
      },
      "correctAnswer": "D",
      "explanation": "GH decreases peripheral glucose uptake and increases hepatic glucose production and insulin secretion, a combination associated with GH-induced insulin resistance.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH decreases peripheral glucose uptake and increases hepatic glucose production and insulin secretion, a combination associated with GH-induced insulin resistance.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 27,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Metabolic Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_028",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH and Bone Growth",
      "question": "Where does growth hormone promote lengthening of long bones during growth?",
      "choices": {
        "A": "Along the periosteal surface",
        "B": "At the epiphyseal cartilages",
        "C": "Along membranous bone surfaces",
        "D": "At closed growth plates"
      },
      "correctAnswer": "B",
      "explanation": "Epiphyseal cartilage supports long-bone lengthening, whereas surface deposition in membranous bone primarily increases thickness.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Epiphyseal cartilage supports long-bone lengthening, whereas surface deposition in membranous bone primarily increases thickness.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 28,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH and Bone Growth",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_029",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH and Bone Growth",
      "question": "In membranous bone, growth hormone promotes surface deposition primarily by stimulating which cells?",
      "choices": {
        "A": "Chondrocytes",
        "B": "Osteoclasts",
        "C": "Osteoblasts",
        "D": "Somatotropes"
      },
      "correctAnswer": "C",
      "explanation": "GH strongly stimulates osteoblasts in membranous bones, supporting continued deposition of new bone on their surfaces.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH strongly stimulates osteoblasts in membranous bones, supporting continued deposition of new bone on their surfaces.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 29,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH and Bone Growth",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_030",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH and Bone Growth",
      "question": "Why can excess growth hormone still thicken certain bones after growth plates close?",
      "choices": {
        "A": "Surface bone deposition by osteoblasts can continue",
        "B": "Epiphyseal cartilage resumes normal lengthening",
        "C": "Chondrocytes replace osteoblast activity",
        "D": "Long bones reopen their growth plates"
      },
      "correctAnswer": "A",
      "explanation": "Although long-bone lengthening stops after growth-plate closure, GH can continue stimulating osteoblasts to deposit bone on membranous surfaces.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Although long-bone lengthening stops after growth-plate closure, GH can continue stimulating osteoblasts to deposit bone on membranous surfaces.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 30,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH and Bone Growth",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_031",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Feedback and Integrated Responses",
      "question": "What is the most likely growth hormone response during exercise accompanied by decreased blood glucose?",
      "choices": {
        "A": "Secretion decreases because both signals are inhibitory",
        "B": "Secretion remains unchanged because the signals cancel",
        "C": "Secretion stops because glucose control dominates",
        "D": "Secretion increases because both signals are stimulatory"
      },
      "correctAnswer": "D",
      "explanation": "Both exercise and decreased blood glucose are listed as stimuli for GH secretion, so their combined direction favors increased release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Both exercise and decreased blood glucose are listed as stimuli for GH secretion, so their combined direction favors increased release.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 31,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Feedback and Integrated Responses",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "PIT_SPRINT_032",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Feedback and Integrated Responses",
      "question": "How does IGF-1 participate in growth hormone feedback according to the lecture figure?",
      "choices": {
        "A": "It stimulates pituitary GH release without hypothalamic effects",
        "B": "It restrains GH output through feedback at the pituitary and hypothalamus",
        "C": "It blocks ghrelin production while directly releasing GHRH",
        "D": "It converts somatostatin into a GH-releasing signal"
      },
      "correctAnswer": "B",
      "explanation": "The feedback figure shows IGF-1 opposing GH output at the pituitary and favoring hypothalamic inhibitory control through somatostatin.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The feedback figure shows IGF-1 opposing GH output at the pituitary and favoring hypothalamic inhibitory control through somatostatin.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 32,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Feedback and Integrated Responses",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "PIT_SPRINT_033",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Feedback and Integrated Responses",
      "question": "Ghrelin in the growth hormone feedback diagram originates from what organ?",
      "choices": {
        "A": "Stomach",
        "B": "Thyroid",
        "C": "Kidney",
        "D": "Adrenal cortex"
      },
      "correctAnswer": "A",
      "explanation": "The GH feedback figure identifies stomach-derived ghrelin as a stimulatory signal to the growth hormone system.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The GH feedback figure identifies stomach-derived ghrelin as a stimulatory signal to the growth hormone system.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 33,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Feedback and Integrated Responses",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_034",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Physiology",
      "subtopic": "GH Feedback and Integrated Responses",
      "question": "An increase in growth hormone is most likely to produce what paired metabolic response?",
      "choices": {
        "A": "Increased adipose glucose uptake and decreased lipolysis",
        "B": "Increased muscle glucose uptake and decreased liver glucose output",
        "C": "Decreased adipose glucose uptake and increased lipolysis",
        "D": "Decreased amino acid uptake and increased protein catabolism"
      },
      "correctAnswer": "C",
      "explanation": "GH shifts fuel use away from glucose in adipose tissue while increasing fat mobilization through lipolysis.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH shifts fuel use away from glucose in adipose tissue while increasing fat mobilization through lipolysis.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 34,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Physiology",
        "concept_group": "GH Feedback and Integrated Responses",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "PIT_SPRINT_035",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Disorders",
      "subtopic": "GH Hyposecretion and Hypersecretion",
      "question": "A child with growth hormone hyposecretion during the growth years is at risk for what condition?",
      "choices": {
        "A": "Acromegaly",
        "B": "Pituitary dwarfism",
        "C": "Gigantism",
        "D": "SIADH"
      },
      "correctAnswer": "B",
      "explanation": "GH hyposecretion during growth slows bone growth and can allow epiphyseal plates to close before normal height is reached.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH hyposecretion during growth slows bone growth and can allow epiphyseal plates to close before normal height is reached.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 35,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Disorders",
        "concept_group": "GH Hyposecretion and Hypersecretion",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_036",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Disorders",
      "subtopic": "GH Hyposecretion and Hypersecretion",
      "question": "Hypersecretion of growth hormone during the growth years most likely produces what condition?",
      "choices": {
        "A": "Pituitary dwarfism",
        "B": "Diabetes insipidus",
        "C": "Acromegaly",
        "D": "Gigantism"
      },
      "correctAnswer": "D",
      "explanation": "Excess GH before growth is complete produces excessive long-bone length, body weight, and muscle mass characteristic of gigantism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Excess GH before growth is complete produces excessive long-bone length, body weight, and muscle mass characteristic of gigantism.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 36,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Disorders",
        "concept_group": "GH Hyposecretion and Hypersecretion",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_037",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Disorders",
      "subtopic": "GH Hyposecretion and Hypersecretion",
      "question": "An adult with thickening of the hands, feet, cheeks, and jaw most likely has which condition?",
      "choices": {
        "A": "Pituitary dwarfism",
        "B": "Gigantism",
        "C": "Acromegaly",
        "D": "Diabetes insipidus"
      },
      "correctAnswer": "C",
      "explanation": "GH hypersecretion in adulthood causes acromegaly, with thickening of characteristic bones and continued soft-tissue growth.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "GH hypersecretion in adulthood causes acromegaly, with thickening of characteristic bones and continued soft-tissue growth.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 37,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Disorders",
        "concept_group": "GH Hyposecretion and Hypersecretion",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_038",
      "unit": "pituitary",
      "conceptBlock": "Growth Hormone Disorders",
      "subtopic": "GH Hyposecretion and Hypersecretion",
      "question": "What best distinguishes gigantism from acromegaly?",
      "choices": {
        "A": "Whether GH hypersecretion begins before or after growth-plate closure",
        "B": "Whether GH secretion is stimulated or inhibited by GHRH",
        "C": "Whether GH acts on adipose tissue or skeletal muscle",
        "D": "Whether GH is produced by somatotropes or lactotrophs"
      },
      "correctAnswer": "A",
      "explanation": "Hypersecretion during growth produces gigantism, whereas hypersecretion after growth-plate closure produces acromegaly.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Hypersecretion during growth produces gigantism, whereas hypersecretion after growth-plate closure produces acromegaly.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 38,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Growth Hormone Disorders",
        "concept_group": "GH Hyposecretion and Hypersecretion",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_039",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "Posterior Pituitary Organization",
      "question": "What is another name for the posterior pituitary?",
      "choices": {
        "A": "Adenohypophysis",
        "B": "Neurohypophysis",
        "C": "Pars distalis",
        "D": "Median eminence"
      },
      "correctAnswer": "B",
      "explanation": "The posterior pituitary is the neurohypophysis, reflecting its neural origin and direct axonal connection with the hypothalamus.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The posterior pituitary is the neurohypophysis, reflecting its neural origin and direct axonal connection with the hypothalamus.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 39,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "Posterior Pituitary Organization",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_040",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "Posterior Pituitary Organization",
      "question": "How do hypothalamic signals reach the posterior pituitary?",
      "choices": {
        "A": "Through portal veins from Rathke's pouch",
        "B": "Through systemic arteries from target organs",
        "C": "Through ducts from the anterior pituitary",
        "D": "Through magnocellular axons descending the pituitary stalk"
      },
      "correctAnswer": "D",
      "explanation": "Magnocellular neurons send axons through the median eminence and down the hypophysial stalk to the posterior pituitary.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Magnocellular neurons send axons through the median eminence and down the hypophysial stalk to the posterior pituitary.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 40,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "Posterior Pituitary Organization",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_041",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "ADH Regulation and Imbalance",
      "question": "If osmolarity rises, what osmolarity-response pairing is expected?",
      "choices": {
        "A": "High osmolarity with decreased ADH release",
        "B": "Low osmolarity with increased ADH release",
        "C": "High osmolarity with increased ADH release",
        "D": "Low osmolarity with unchanged ADH release"
      },
      "correctAnswer": "C",
      "explanation": "Osmoreceptors respond to high osmolarity by increasing ADH, which promotes renal water reabsorption.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Osmoreceptors respond to high osmolarity by increasing ADH, which promotes renal water reabsorption.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 41,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "ADH Regulation and Imbalance",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_042",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "ADH Regulation and Imbalance",
      "question": "During high atrial stretch and blood pressure, how is ADH release expected to change?",
      "choices": {
        "A": "ADH release decreases",
        "B": "ADH release increases",
        "C": "ADH release remains unchanged",
        "D": "ADH release is delayed"
      },
      "correctAnswer": "A",
      "explanation": "High pressure detected through atrial stretch receptors and baroreceptors decreases ADH release; low pressure has the opposite effect.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "High pressure detected through atrial stretch receptors and baroreceptors decreases ADH release; low pressure has the opposite effect.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 42,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "ADH Regulation and Imbalance",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_043",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "ADH Regulation and Imbalance",
      "question": "What combination is expected when ADH activity is too low?",
      "choices": {
        "A": "More water reabsorption and less urine",
        "B": "More water reabsorption and more urine",
        "C": "Less water reabsorption and less urine",
        "D": "Less water reabsorption and more urine"
      },
      "correctAnswer": "D",
      "explanation": "Reduced ADH activity limits renal water reabsorption, increasing urine output as illustrated for diabetes insipidus.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Reduced ADH activity limits renal water reabsorption, increasing urine output as illustrated for diabetes insipidus.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 43,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "ADH Regulation and Imbalance",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "PIT_SPRINT_044",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "ADH Regulation and Imbalance",
      "question": "A patient with SIADH is most likely to show which electrolyte abnormality?",
      "choices": {
        "A": "Hypernatremia",
        "B": "Hyponatremia",
        "C": "Hyperkalemia",
        "D": "Hypokalemia"
      },
      "correctAnswer": "B",
      "explanation": "SIADH is associated with hyponatremia; diabetes insipidus represents deficient ADH activity or response rather than inappropriate excess.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "SIADH is associated with hyponatremia; diabetes insipidus represents deficient ADH activity or response rather than inappropriate excess.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 44,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "ADH Regulation and Imbalance",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "PIT_SPRINT_045",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "Oxytocin Actions and Reflex",
      "question": "During breastfeeding, oxytocin directly causes which event?",
      "choices": {
        "A": "Prolactin release from lactotrophs",
        "B": "Milk synthesis by mammary gland cells",
        "C": "Contraction of mammary myoepithelial cells",
        "D": "Relaxation of uterine smooth muscle"
      },
      "correctAnswer": "C",
      "explanation": "Oxytocin contracts myoepithelial cells for milk ejection, whereas prolactin supports milk production.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Oxytocin contracts myoepithelial cells for milk ejection, whereas prolactin supports milk production.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 45,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "Oxytocin Actions and Reflex",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "PIT_SPRINT_046",
      "unit": "pituitary",
      "conceptBlock": "Posterior Pituitary Hormones",
      "subtopic": "Oxytocin Actions and Reflex",
      "question": "Following nipple suckling, what sequence produces oxytocin-mediated milk ejection?",
      "choices": {
        "A": "Nipple suckling to sensory nerves to PVN activation to oxytocin release to myoepithelial contraction",
        "B": "Nipple suckling to PVN activation to myoepithelial contraction to oxytocin release to sensory nerves",
        "C": "Nipple suckling to sensory nerves to dopamine release to lactotroph inhibition to milk ejection",
        "D": "Nipple suckling to osmoreceptors to ADH release to renal water retention to milk ejection"
      },
      "correctAnswer": "A",
      "explanation": "Suckling sends sensory input to the PVN, leading to oxytocin release and contraction of mammary myoepithelial cells that ejects milk.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Suckling sends sensory input to the PVN, leading to oxytocin release and contraction of mammary myoepithelial cells that ejects milk.",
      "bankId": "pituitary_sprint_v2_2",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Pituitary Hormones and Their Control by the Hypothalamus",
      "sourceOrder": 46,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 Lecture - Pituitary Hormones and their Control by the Hypothalamus",
        "broad_category": "Posterior Pituitary Hormones",
        "concept_group": "Oxytocin Actions and Reflex",
        "learning_level": "Integrative"
      }
    }
  ]
};
window.PITUITARY_SPRINT_QUESTIONS = window.PITUITARY_SPRINT_BANK.questions;
