window.THYROID_SPRINT_BANK = {
  "schemaVersion": "1.0.0",
  "bankId": "thyroid_sprint_v2_3",
  "bankType": "sprint",
  "mode": "learn",
  "sourceLecture": "Thyroid Gland and Thyroid Hormones",
  "questionCount": 41,
  "questions": [
    {
      "id": "THYR_SPRINT_001",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Anatomy & Cells",
      "subtopic": "Location of Thyroid",
      "question": "Where is the thyroid gland located?",
      "choices": {
        "A": "Superior to the larynx and posterior to the trachea",
        "B": "Inferior to the larynx and anterior to the trachea",
        "C": "Within the larynx and lateral to the trachea",
        "D": "Inside the lumen of a thyroid follicle"
      },
      "correctAnswer": "B",
      "explanation": "The thyroid lies in the anterior neck, inferior to the larynx and anterior to the trachea.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The thyroid lies in the anterior neck, inferior to the larynx and anterior to the trachea.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 1,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Anatomy & Cells",
        "concept_group": "Location of Thyroid",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_002",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Anatomy & Cells",
      "subtopic": "Gross Anatomy",
      "question": "Which description matches the gross anatomy of the thyroid gland?",
      "choices": {
        "A": "A cuboidal cell layer surrounding colloid",
        "B": "A central lumen filled with thyroglobulin",
        "C": "Parafollicular cells between follicles",
        "D": "Two lateral lobes connected by an isthmus"
      },
      "correctAnswer": "D",
      "explanation": "Gross anatomy describes the whole organ, which consists of two lateral lobes joined by an isthmus.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Gross anatomy describes the whole organ, which consists of two lateral lobes joined by an isthmus.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 2,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Anatomy & Cells",
        "concept_group": "Gross Anatomy",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_003",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Anatomy & Cells",
      "subtopic": "Microscopic Anatomy (Follicles)",
      "question": "Moving from the outer edge of a thyroid follicle toward its center, which order is correct?",
      "choices": {
        "A": "Follicular cells, colloid",
        "B": "Colloid, follicular cells",
        "C": "C-cells, thyroid lobe",
        "D": "Isthmus, follicular cells"
      },
      "correctAnswer": "A",
      "explanation": "The follicular cells form the wall; the colloid occupies the central lumen inside that wall.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The follicular cells form the wall; the colloid occupies the central lumen inside that wall.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 3,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Anatomy & Cells",
        "concept_group": "Microscopic Anatomy (Follicles)",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_004",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Anatomy & Cells",
      "subtopic": "Colloid & Thyroglobulin",
      "question": "In a thyroid-follicle model, the central lumen can no longer retain thyroglobulin. Which function is most directly reduced?",
      "choices": {
        "A": "Connecting the two thyroid lobes",
        "B": "Forming the cuboidal follicular wall",
        "C": "Storing thyroid-hormone precursors in colloid",
        "D": "Secreting calcitonin from C-cells"
      },
      "correctAnswer": "C",
      "explanation": "Thyroglobulin in luminal colloid carries stored thyroid-hormone precursors, so loss of its retention directly reduces that extracellular reservoir.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroglobulin in luminal colloid carries stored thyroid-hormone precursors, so loss of its retention directly reduces that extracellular reservoir.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 4,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Anatomy & Cells",
        "concept_group": "Colloid & Thyroglobulin",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_005",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Anatomy & Cells",
      "subtopic": "Follicular Cells",
      "question": "Which comparison of thyroid cell types is correct?",
      "choices": {
        "A": "Follicular cells and C-cells both fill the follicular lumen.",
        "B": "Follicular cells line follicles, while C-cells are parafollicular and secrete calcitonin.",
        "C": "Follicular cells secrete calcitonin, while C-cells store thyroglobulin.",
        "D": "Follicular cells form the isthmus, while C-cells form the thyroid lobes."
      },
      "correctAnswer": "B",
      "explanation": "Follicular cells form the epithelial lining of follicles; C-cells are parafollicular cells with calcitonin secretion as their distinguishing function.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Follicular cells form the epithelial lining of follicles; C-cells are parafollicular cells with calcitonin secretion as their distinguishing function.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 5,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Anatomy & Cells",
        "concept_group": "Follicular Cells",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_006",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Anatomy & Cells",
      "subtopic": "C-Cells (Parafollicular Cells)",
      "question": "Blood calcium rises and a thyroid cell releases calcitonin. Which cell responded?",
      "choices": {
        "A": "C-cell (parafollicular cell)",
        "B": "Follicular cell",
        "C": "Colloid",
        "D": "Isthmus cell"
      },
      "correctAnswer": "A",
      "explanation": "C-cells are the parafollicular thyroid cells that secrete calcitonin as part of blood-calcium regulation.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "C-cells are the parafollicular thyroid cells that secrete calcitonin as part of blood-calcium regulation.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 6,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Anatomy & Cells",
        "concept_group": "C-Cells (Parafollicular Cells)",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_007",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Iodide Trapping (NIS)",
      "question": "A follicular cell cannot move iodide from blood across its basolateral membrane. Which transporter is impaired?",
      "choices": {
        "A": "Pendrin",
        "B": "Thyroglobulin",
        "C": "Deiodinase",
        "D": "NIS"
      },
      "correctAnswer": "D",
      "explanation": "NIS performs basolateral iodide trapping from blood.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "NIS performs basolateral iodide trapping from blood.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 7,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Iodide Trapping (NIS)",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_008",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Pendrin",
      "question": "Iodide enters a follicular cell but cannot reach the colloid. Which transporter is most likely impaired?",
      "choices": {
        "A": "NIS",
        "B": "TBG",
        "C": "Pendrin",
        "D": "Thyroid receptor"
      },
      "correctAnswer": "C",
      "explanation": "Pendrin transfers iodide across the apical membrane into the lumen.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Pendrin transfers iodide across the apical membrane into the lumen.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 8,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Pendrin",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_009",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Thyroglobulin Synthesis",
      "question": "Which change would most directly remove the tyrosine scaffold used to assemble thyroid hormone?",
      "choices": {
        "A": "Failure to synthesize thyroglobulin",
        "B": "Failure to secrete calcitonin",
        "C": "Increased albumin binding",
        "D": "Increased beta-1 receptors"
      },
      "correctAnswer": "A",
      "explanation": "Thyroglobulin supplies the tyrosine residues that are iodinated and coupled.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroglobulin supplies the tyrosine residues that are iodinated and coupled.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 9,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Thyroglobulin Synthesis",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_010",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Oxidation of Iodide",
      "question": "Iodide reaches the apical surface but is not converted into reactive iodine. Which step failed?",
      "choices": {
        "A": "Iodide trapping by NIS",
        "B": "Oxidation of iodide",
        "C": "Colloid endocytosis",
        "D": "T4 transport by TBG"
      },
      "correctAnswer": "B",
      "explanation": "Oxidation creates the reactive iodine form required for attachment to tyrosine.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Oxidation creates the reactive iodine form required for attachment to tyrosine.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 10,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Oxidation of Iodide",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_011",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Peroxidase",
      "question": "Inhibition of thyroid peroxidase prevents reactive iodine formation and its attachment to thyroglobulin. Which pair names those reactions?",
      "choices": {
        "A": "NIS transport and Pendrin transport",
        "B": "T4 binding and T3 binding",
        "C": "TRH release and TSH release",
        "D": "Iodide oxidation and organification"
      },
      "correctAnswer": "D",
      "explanation": "TPO catalyzes iodide oxidation and organification at the apical interface.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "TPO catalyzes iodide oxidation and organification at the apical interface.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 11,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Peroxidase",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "THYR_SPRINT_012",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Organification",
      "question": "Reactive iodine is available, but it cannot attach to thyroglobulin tyrosines. Which process is defective?",
      "choices": {
        "A": "Coupling",
        "B": "Proteolysis",
        "C": "Organification",
        "D": "Negative feedback"
      },
      "correctAnswer": "C",
      "explanation": "Organification is the iodination of tyrosine residues on thyroglobulin.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Organification is the iodination of tyrosine residues on thyroglobulin.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 12,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Organification",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_013",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Coupling",
      "question": "MIT and DIT form normally, but T3 and T4 do not form. Which step is impaired?",
      "choices": {
        "A": "Coupling",
        "B": "Iodide trapping",
        "C": "Organification",
        "D": "TBG binding"
      },
      "correctAnswer": "A",
      "explanation": "Coupling joins iodinated tyrosines to create T3 and T4.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Coupling joins iodinated tyrosines to create T3 and T4.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 13,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Coupling",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_014",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "MIT & DIT",
      "question": "Which pairing correctly identifies the iodinated tyrosine precursors?",
      "choices": {
        "A": "MIT has two iodines; DIT has one",
        "B": "MIT is T3; DIT is T4",
        "C": "MIT is a carrier; DIT is a receptor",
        "D": "MIT has one iodine; DIT has two"
      },
      "correctAnswer": "D",
      "explanation": "The names distinguish mono- from di-iodotyrosine.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The names distinguish mono- from di-iodotyrosine.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 14,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "MIT & DIT",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_015",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "T3 & T4 Formation",
      "question": "Which statement correctly compares T3 and T4?",
      "choices": {
        "A": "NIS moves iodide from blood into a follicular cell across its basolateral membrane.",
        "B": "T3 contains three iodine atoms; T4 contains four and both regulate metabolism and development.",
        "C": "Pendrin moves iodide across the apical membrane into the follicular lumen.",
        "D": "Thyroglobulin is a tyrosine-rich scaffold made in RER/Golgi and secreted into colloid."
      },
      "correctAnswer": "B",
      "explanation": "T3 contains three iodine atoms and T4 contains four; both contribute to metabolic regulation, growth, and development.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "T3 contains three iodine atoms and T4 contains four; both contribute to metabolic regulation, growth, and development.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 15,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "T3 & T4 Formation",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_016",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Storage in Colloid",
      "question": "Why can stored thyroid hormone support the body after new synthesis falls?",
      "choices": {
        "A": "T3 is stored inside C-cells",
        "B": "TSH is stored in the isthmus",
        "C": "A large thyroglobulin-bound reservoir remains in colloid",
        "D": "Albumin produces new T4"
      },
      "correctAnswer": "C",
      "explanation": "Colloid holds a substantial extracellular reservoir on thyroglobulin.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Colloid holds a substantial extracellular reservoir on thyroglobulin.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 16,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Storage in Colloid",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_017",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Secretion (Pinocytosis & Proteolysis)",
      "question": "Lysosomal proteolysis of endocytosed colloid is blocked. What falls most directly?",
      "choices": {
        "A": "Iodide entry through NIS",
        "B": "Release of free T3 and T4",
        "C": "TRH secretion",
        "D": "TBG synthesis"
      },
      "correctAnswer": "B",
      "explanation": "Proteolysis frees T3 and T4 from internalized thyroglobulin before release.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Proteolysis frees T3 and T4 from internalized thyroglobulin before release.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 17,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Secretion (Pinocytosis & Proteolysis)",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_018",
      "unit": "thyroid",
      "conceptBlock": "Hormone Synthesis & Release",
      "subtopic": "Deiodinase",
      "question": "Reduced deiodinase activity would directly impair which processes?",
      "choices": {
        "A": "Iodine recycling and T4-to-T3 conversion",
        "B": "Iodide trapping and Pendrin transport",
        "C": "TRH and TSH synthesis",
        "D": "TBG and albumin production"
      },
      "correctAnswer": "A",
      "explanation": "Deiodinases remove iodine from MIT/DIT and convert T4 to T3.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Deiodinases remove iodine from MIT/DIT and convert T4 to T3.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 18,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Hormone Synthesis & Release",
        "concept_group": "Deiodinase",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "THYR_SPRINT_019",
      "unit": "thyroid",
      "conceptBlock": "Blood Transport & Binding",
      "subtopic": "Plasma Protein Transport",
      "question": "Which statement describes thyroid hormone transport in blood?",
      "choices": {
        "A": "Most T3 and T4 circulate freely without plasma proteins.",
        "B": "T3 and T4 are carried mainly inside red blood cells.",
        "C": "Most T3 and T4 circulate bound to plasma proteins, especially thyroxine-binding globulin.",
        "D": "Only T3 binds plasma proteins while T4 remains free."
      },
      "correctAnswer": "C",
      "explanation": "About 99% of circulating thyroid hormone is protein-bound; the lecture identifies thyroxine-binding globulin, prealbumin, and albumin as carriers.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "About 99% of circulating thyroid hormone is protein-bound; the lecture identifies thyroxine-binding globulin, prealbumin, and albumin as carriers.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 19,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Blood Transport & Binding",
        "concept_group": "Plasma Protein Transport",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_020",
      "unit": "thyroid",
      "conceptBlock": "Blood Transport & Binding",
      "subtopic": "Affinity & Half-Life",
      "question": "Which hormone remains in blood longer because it binds carrier proteins more strongly?",
      "choices": {
        "A": "T3",
        "B": "TRH",
        "C": "TSH",
        "D": "T4"
      },
      "correctAnswer": "D",
      "explanation": "The source assigns T4 the higher affinity and approximately six-day half-life.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The source assigns T4 the higher affinity and approximately six-day half-life.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 20,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Blood Transport & Binding",
        "concept_group": "Affinity & Half-Life",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_021",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Genomic Mechanism",
      "question": "A thyroid-hormone response requires new protein synthesis. Which mechanism best explains it?",
      "choices": {
        "A": "T3 binding a nuclear receptor and changing transcription",
        "B": "T3 filling the follicular lumen",
        "C": "T4 binding NIS",
        "D": "Calcitonin activating thyroglobulin"
      },
      "correctAnswer": "A",
      "explanation": "Genomic thyroid action begins at a nuclear receptor and alters transcription.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Genomic thyroid action begins at a nuclear receptor and alters transcription.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 21,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Genomic Mechanism",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_022",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Non-Genomic Effects",
      "question": "What distinguishes a non-genomic thyroid-hormone effect?",
      "choices": {
        "A": "T3 binds a nuclear receptor on DNA and changes gene transcription and protein synthesis.",
        "B": "Thyroid hormone increases mitochondrial number, size, activity, ATP production, and heat.",
        "C": "Non-genomic thyroid effects are rapid and do not require new gene transcription.",
        "D": "Thyroid hormone stimulates Na+/K+-ATPase, increasing ATP use and heat production."
      },
      "correctAnswer": "C",
      "explanation": "Non-genomic effects occur rapidly through mechanisms outside new gene transcription, including membrane, cytoplasmic, and mitochondrial actions.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Non-genomic effects occur rapidly through mechanisms outside new gene transcription, including membrane, cytoplasmic, and mitochondrial actions.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 22,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Non-Genomic Effects",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_023",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Mitochondrial Effects",
      "question": "Excess thyroid hormone increases heat production. Which mitochondrial change contributes?",
      "choices": {
        "A": "Loss of all mitochondria",
        "B": "Increased mitochondrial number and enzymatic activity",
        "C": "Reduced ATP production",
        "D": "Blocked oxidative phosphorylation"
      },
      "correctAnswer": "B",
      "explanation": "Thyroid hormone increases mitochondrial capacity, ATP production, and heat.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroid hormone increases mitochondrial capacity, ATP production, and heat.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 23,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Mitochondrial Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_024",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Na/K ATPase Effects",
      "question": "Why does thyroid stimulation of Na+/K+-ATPase increase heat production?",
      "choices": {
        "A": "The pump stores T4",
        "B": "The pump secretes TSH",
        "C": "The pump binds catecholamines",
        "D": "The pump consumes more ATP"
      },
      "correctAnswer": "D",
      "explanation": "Greater pump activity increases ATP consumption and its calorigenic effect.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Greater pump activity increases ATP consumption and its calorigenic effect.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 24,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Na/K ATPase Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_025",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Cardiovascular Effects",
      "question": "Which change best explains thyroid-hormone-associated tachycardia?",
      "choices": {
        "A": "Increased beta-1 adrenergic responsiveness",
        "B": "Reduced mitochondrial activity",
        "C": "Decreased cardiac output",
        "D": "Loss of catecholamine sensitivity"
      },
      "correctAnswer": "A",
      "explanation": "Thyroid hormone increases beta-1 responsiveness, raising heart rate and output.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroid hormone increases beta-1 responsiveness, raising heart rate and output.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 25,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Cardiovascular Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_026",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Metabolic Effects (Carbs & Fats)",
      "question": "Which metabolic pattern is most consistent with excess thyroid hormone?",
      "choices": {
        "A": "Reduced glucose absorption",
        "B": "Increased lipolysis and fatty-acid oxidation",
        "C": "Reduced glycolysis",
        "D": "Increased plasma cholesterol from reduced lipid use"
      },
      "correctAnswer": "B",
      "explanation": "Excess thyroid hormone accelerates both carbohydrate and lipid metabolism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Excess thyroid hormone accelerates both carbohydrate and lipid metabolism.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 26,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Metabolic Effects (Carbs & Fats)",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_027",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Growth & CNS Effects",
      "question": "Severe thyroid-hormone deficiency during infancy most directly threatens which processes?",
      "choices": {
        "A": "Colloid formation only",
        "B": "Albumin synthesis only",
        "C": "Brain maturation and skeletal development",
        "D": "Calcitonin release only"
      },
      "correctAnswer": "C",
      "explanation": "Thyroid hormone is essential for fetal brain maturation and supports skeletal growth.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroid hormone is essential for fetal brain maturation and supports skeletal growth.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 27,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Growth & CNS Effects",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "THYR_SPRINT_028",
      "unit": "thyroid",
      "conceptBlock": "Physiologic Effects",
      "subtopic": "Sympathomimetic Effects",
      "question": "How does thyroid hormone produce sympathomimetic effects?",
      "choices": {
        "A": "T3 binds a nuclear receptor on DNA and changes gene transcription and protein synthesis.",
        "B": "Non-genomic thyroid effects are rapid and do not require new gene transcription.",
        "C": "Thyroid hormone increases mitochondrial number, size, activity, ATP production, and heat.",
        "D": "Thyroid hormone increases beta-adrenergic sensitivity to catecholamines."
      },
      "correctAnswer": "D",
      "explanation": "Thyroid hormone increases tissue responsiveness to catecholamines by increasing beta-adrenergic sensitivity.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroid hormone increases tissue responsiveness to catecholamines by increasing beta-adrenergic sensitivity.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 28,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Physiologic Effects",
        "concept_group": "Sympathomimetic Effects",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_029",
      "unit": "thyroid",
      "conceptBlock": "HPT-Axis Regulation",
      "subtopic": "HPT Axis",
      "question": "A primary thyroid failure lowers T3/T4. What should intact feedback do to TSH?",
      "choices": {
        "A": "Decrease TSH",
        "B": "Increase TSH",
        "C": "Leave TSH permanently absent",
        "D": "Convert TSH into TRH"
      },
      "correctAnswer": "B",
      "explanation": "Low thyroid hormone removes negative feedback, allowing TSH to rise.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Low thyroid hormone removes negative feedback, allowing TSH to rise.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 29,
      "learningLevel": "Integrative",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "HPT-Axis Regulation",
        "concept_group": "HPT Axis",
        "learning_level": "Integrative"
      }
    },
    {
      "id": "THYR_SPRINT_030",
      "unit": "thyroid",
      "conceptBlock": "HPT-Axis Regulation",
      "subtopic": "TRH",
      "question": "Which event occurs directly after hypothalamic TRH reaches the anterior pituitary?",
      "choices": {
        "A": "TSH synthesis and release increase",
        "B": "T3 binds TBG",
        "C": "Colloid is proteolyzed directly by TRH",
        "D": "C-cells release calcitonin"
      },
      "correctAnswer": "A",
      "explanation": "TRH acts on the anterior pituitary to stimulate TSH.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "TRH acts on the anterior pituitary to stimulate TSH.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 30,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "HPT-Axis Regulation",
        "concept_group": "TRH",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_031",
      "unit": "thyroid",
      "conceptBlock": "HPT-Axis Regulation",
      "subtopic": "TSH Effects",
      "question": "Persistently elevated TSH would be expected to cause which chronic thyroid change?",
      "choices": {
        "A": "Loss of all follicular cells",
        "B": "Reduced iodide trapping",
        "C": "Suppression of every synthesis step",
        "D": "Follicular-cell hypertrophy and hyperplasia"
      },
      "correctAnswer": "D",
      "explanation": "Chronic TSH increases follicular-cell size and number.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Chronic TSH increases follicular-cell size and number.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 31,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "HPT-Axis Regulation",
        "concept_group": "TSH Effects",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_032",
      "unit": "thyroid",
      "conceptBlock": "HPT-Axis Regulation",
      "subtopic": "Negative Feedback",
      "question": "Circulating T3 and T4 rise. What should happen to upstream HPT-axis hormones?",
      "choices": {
        "A": "TRH and TSH increase",
        "B": "TRH rises while TSH is unchanged",
        "C": "TRH and TSH decrease",
        "D": "TSH converts into T4"
      },
      "correctAnswer": "C",
      "explanation": "T3/T4 inhibit both TRH and TSH through negative feedback.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "T3/T4 inhibit both TRH and TSH through negative feedback.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 32,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "HPT-Axis Regulation",
        "concept_group": "Negative Feedback",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_033",
      "unit": "thyroid",
      "conceptBlock": "HPT-Axis Regulation",
      "subtopic": "Neurogenic Stimuli",
      "question": "How do cold, fasting, and stress affect the HPT axis according to the lecture?",
      "choices": {
        "A": "Cold increases TRH/TSH, whereas fasting and stress decrease TRH/TSH.",
        "B": "The HPT axis is TRH from hypothalamus, TSH from anterior pituitary, then T3/T4 from thyroid.",
        "C": "Hypothalamic TRH stimulates TSH synthesis and release from the anterior pituitary.",
        "D": "Anterior-pituitary TSH stimulates thyroid-hormone synthesis, release, and follicular-cell growth."
      },
      "correctAnswer": "A",
      "explanation": "Cold stimulates TRH and TSH, whereas fasting and stress-related stimuli suppress them.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Cold stimulates TRH and TSH, whereas fasting and stress-related stimuli suppress them.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 33,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "HPT-Axis Regulation",
        "concept_group": "Neurogenic Stimuli",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_034",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Hyperthyroidism (Graves')",
      "question": "Which laboratory pattern supports primary hyperthyroidism?",
      "choices": {
        "A": "High TSH and low free T4",
        "B": "Low TSH and high free T4",
        "C": "High TSH and high free T4",
        "D": "Low TSH and low free T4"
      },
      "correctAnswer": "B",
      "explanation": "Excess thyroid output suppresses pituitary TSH through feedback.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Excess thyroid output suppresses pituitary TSH through feedback.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 34,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Hyperthyroidism (Graves')",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_035",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Hypothyroidism (Hashimoto's)",
      "question": "Which laboratory pattern is most consistent with primary hypothyroidism caused by Hashimoto disease?",
      "choices": {
        "A": "Primary hyperthyroidism produces excess thyroid hormone, typically high free T4 and low TSH.",
        "B": "Exophthalmos is protrusion of the eyes from autoimmune inflammation behind the eyes in Graves disease.",
        "C": "Myxedema is non-pitting edema caused by glycosaminoglycan accumulation in hypothyroidism.",
        "D": "Primary hypothyroidism produces deficient thyroid hormone, typically low free T4 and high TSH."
      },
      "correctAnswer": "D",
      "explanation": "Destruction of thyroid tissue in Hashimoto disease lowers free T4; reduced negative feedback allows TSH to rise.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Destruction of thyroid tissue in Hashimoto disease lowers free T4; reduced negative feedback allows TSH to rise.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 35,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Hypothyroidism (Hashimoto's)",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_036",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Cretinism",
      "question": "Why is severe thyroid-hormone deficiency in infancy especially harmful?",
      "choices": {
        "A": "It raises free T4",
        "B": "It causes excess TSH feedback inhibition",
        "C": "It impairs brain and skeletal development",
        "D": "It increases beta-1 sensitivity"
      },
      "correctAnswer": "C",
      "explanation": "Thyroid hormone is essential for early neural and skeletal development.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Thyroid hormone is essential for early neural and skeletal development.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 36,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Cretinism",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_037",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Diagnostic Testing",
      "question": "A patient has low free T4 and elevated TSH. Which interpretation fits the source?",
      "choices": {
        "A": "Primary hyperthyroidism",
        "B": "Primary hypothyroidism",
        "C": "Normal thyroid function with Graves TSI",
        "D": "Exophthalmos without thyroid dysfunction"
      },
      "correctAnswer": "B",
      "explanation": "Primary thyroid failure lowers free T4 and raises TSH through reduced feedback.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "Primary thyroid failure lowers free T4 and raises TSH through reduced feedback.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 37,
      "learningLevel": "Applied Reinforcement",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Diagnostic Testing",
        "learning_level": "Applied Reinforcement"
      }
    },
    {
      "id": "THYR_SPRINT_038",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Hyperthyroidism Treatment",
      "question": "Which treatment was listed for hyperthyroidism in the lecture?",
      "choices": {
        "A": "Propylthiouracil",
        "B": "Exogenous thyroxine",
        "C": "Insulin",
        "D": "Calcitonin"
      },
      "correctAnswer": "A",
      "explanation": "The lecture lists propylthiouracil, radioactive iodine, and surgical removal as treatments for hyperthyroidism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The lecture lists propylthiouracil, radioactive iodine, and surgical removal as treatments for hyperthyroidism.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 38,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Hyperthyroidism Treatment",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_039",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Hypothyroidism Treatment",
      "question": "Which treatment replaces the deficient hormone in hypothyroidism?",
      "choices": {
        "A": "Propylthiouracil",
        "B": "Radioactive iodine",
        "C": "Thyroid removal",
        "D": "Exogenous thyroxine"
      },
      "correctAnswer": "D",
      "explanation": "The lecture identifies exogenous thyroxine as replacement treatment for hypothyroidism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The lecture identifies exogenous thyroxine as replacement treatment for hypothyroidism.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 39,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Hypothyroidism Treatment",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_040",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Exophthalmos",
      "question": "Which physical finding did the lecture associate with hyperthyroidism?",
      "choices": {
        "A": "Myxedema",
        "B": "Cretinism",
        "C": "Exophthalmos",
        "D": "Colloid goiter"
      },
      "correctAnswer": "C",
      "explanation": "The hyperthyroidism slides identify exophthalmos, or protruding eyes, as a characteristic physical finding.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The hyperthyroidism slides identify exophthalmos, or protruding eyes, as a characteristic physical finding.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 40,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Exophthalmos",
        "learning_level": "Foundation"
      }
    },
    {
      "id": "THYR_SPRINT_041",
      "unit": "thyroid",
      "conceptBlock": "Thyroid Disorders & Testing",
      "subtopic": "Myxedema",
      "question": "Which sign did the lecture associate with hypothyroidism?",
      "choices": {
        "A": "Exophthalmos",
        "B": "Myxedema",
        "C": "Hand tremor",
        "D": "Increased sweating"
      },
      "correctAnswer": "B",
      "explanation": "The hypothyroidism slides list myxedema as a characteristic sign, whereas exophthalmos is associated with hyperthyroidism.",
      "commonPitfall": "",
      "teachingTag": "",
      "teachingCardId": "",
      "miniGuide": "The hypothyroidism slides list myxedema as a characteristic sign, whereas exophthalmos is associated with hyperthyroidism.",
      "bankId": "thyroid_sprint_v2_3",
      "bankType": "sprint",
      "sessionMode": "learn",
      "sourceLecture": "Thyroid Gland and Thyroid Hormones",
      "sourceOrder": 41,
      "learningLevel": "Foundation",
      "metadata": {
        "source": "WI 26 Week 10 - Thyroid gland and thyroid hormone.pdf",
        "broad_category": "Thyroid Disorders & Testing",
        "concept_group": "Myxedema",
        "learning_level": "Foundation"
      }
    }
  ]
};
window.THYROID_SPRINT_QUESTIONS = window.THYROID_SPRINT_BANK.questions;
