(function () {
  "use strict";

  const indicators = (bloodGlucose, insulin, glucagon, tissueUptake, hepaticOutput, urinaryGlucose, ketones) => ({
    bloodGlucose, insulin, glucagon, tissueUptake, hepaticOutput, urinaryGlucose, ketones
  });

  const shared = [
    { id: "meal", order: 1, title: "Meal", location: "Meal begins", icon: "◉", movingItem: "Meal", mainEvent: "A carbohydrate-containing meal enters the digestive pathway.", trigger: "Eating begins the fed-state sequence.", next: "Food is mechanically processed in the mouth.", basic: "Carbohydrate enters the body, but circulating glucose has not changed yet.", organ: "The gastrointestinal tract receives the meal and prepares it for digestion.", cellular: "No condition-specific transporter or hormone response is required at this checkpoint." },
    { id: "mouth", order: 2, title: "Mouth", location: "Oral cavity", icon: "◇", movingItem: "Meal", mainEvent: "Chewing breaks the meal into smaller pieces and carbohydrate digestion begins.", trigger: "The meal enters the oral cavity.", next: "The swallowed meal moves to the stomach.", basic: "Meal processing is essentially the same in all three conditions at this point.", organ: "The mouth mechanically processes food before swallowing.", cellular: "The diabetes models do not alter this early oral-processing step." },
    { id: "stomach", order: 3, title: "Stomach", location: "Upper gastrointestinal tract", icon: "◒", movingItem: "Meal", mainEvent: "The stomach mixes the meal and controls its delivery to the small intestine.", trigger: "Swallowed food reaches the stomach.", next: "Carbohydrate-containing material enters the small intestine.", basic: "Gastric processing remains similar before glucose enters the blood.", organ: "The stomach mixes the meal and meters delivery into the small intestine.", cellular: "Condition-specific glucose regulation has not yet become the dominant event." },
    { id: "small-intestine", order: 4, title: "Small Intestine", location: "Intestinal lumen and epithelium", icon: "≈", movingItem: "Glucose", mainEvent: "Carbohydrate is reduced to absorbable sugars, and glucose crosses the intestinal epithelium.", trigger: "Digestive products arrive in the small intestine.", next: "Absorbed glucose enters hepatic portal blood.", basic: "Glucose absorption raises the amount of glucose entering the circulation.", organ: "The small intestine completes carbohydrate digestion and transfers glucose into portal blood.", cellular: "Intestinal sodium-glucose transport is insulin independent; diabetes does not prevent intestinal glucose absorption." },
    { id: "portal-blood", order: 5, title: "Portal Blood", location: "Hepatic portal circulation", icon: "↟", movingItem: "Glucose", mainEvent: "Absorbed glucose travels first toward the liver, and circulating glucose begins to rise.", trigger: "Glucose leaves the intestinal epithelium.", next: "The liver receives nutrient-rich portal blood.", basic: "The post-meal glucose rise is now visible in the circulation.", organ: "Portal blood delivers absorbed glucose directly to the liver before wider systemic distribution.", cellular: "The rise in circulating glucose also provides the signal that pancreatic beta cells will detect." },
    { id: "liver", order: 6, title: "Liver", location: "Hepatic tissue", icon: "⬡", movingItem: "Glucose", mainEvent: "The liver begins deciding whether to use, store, or release glucose.", trigger: "Glucose-rich portal blood reaches hepatocytes.", next: "The endocrine pancreas coordinates the hormonal response.", basic: "Liver handling determines whether glucose is stored or continues circulating.", organ: "The liver acts as a blood-glucose buffer by changing glucose storage and output.", cellular: "Insulin supports hepatic glucose use and glycogen synthesis while opposing glycogen breakdown and gluconeogenesis." },
    { id: "pancreas", order: 7, title: "Pancreas", location: "Pancreatic islets", icon: "✦", movingItem: "Insulin", mainEvent: "Pancreatic islet cells respond to the post-meal glucose signal.", trigger: "Blood glucose has risen after intestinal absorption.", next: "The resulting insulin signal travels to target tissues.", basic: "Beta-cell insulin output and relative glucagon suppression set the fed-state response.", organ: "Beta cells release insulin; alpha-cell glucagon output is relatively lower after a carbohydrate meal.", cellular: "Glucose entry into beta cells raises ATP, closes potassium channels, depolarizes the membrane, opens calcium channels, and triggers insulin-vesicle release." },
    { id: "insulin-signal", order: 8, title: "Insulin Signal", location: "Blood and target tissues", icon: "✧", movingItem: "Insulin", mainEvent: "Insulin reaches responsive tissues and signals that fuel is available.", trigger: "Pancreatic beta cells release insulin.", next: "Muscle and adipose tissue alter glucose uptake and storage.", basic: "The effectiveness of this signal now separates the three conditions.", organ: "Insulin coordinates liver, skeletal muscle, and adipose responses to the meal.", cellular: "Insulin-receptor signaling promotes GLUT4 movement to the membrane in skeletal muscle and adipose cells." },
    { id: "muscle-adipose", order: 9, title: "Muscle and Adipose Tissue", location: "Peripheral target tissues", icon: "⬢", movingItem: "Glucose", mainEvent: "Skeletal muscle and adipose tissue respond to the insulin signal.", trigger: "Insulin reaches its target tissues after the meal.", next: "The balance of uptake, storage, and hepatic output determines the blood-glucose course.", basic: "Peripheral uptake determines how efficiently glucose leaves the blood.", organ: "Skeletal muscle can use or store glucose as glycogen; adipose tissue uses glucose to support fat storage.", cellular: "Effective insulin signaling increases surface GLUT4 in skeletal muscle and adipocytes; insulin also inhibits hormone-sensitive lipase." },
    { id: "baseline", order: 10, title: "Blood Glucose Returns Toward Baseline", location: "Systemic circulation", icon: "◎", movingItem: "Glucose", mainEvent: "The accumulated organ responses determine whether blood glucose resolves after the meal.", trigger: "Intestinal glucose entry slows while tissue handling continues.", next: "The body later shifts from the fed state toward fasting.", basic: "This checkpoint reveals whether the post-meal response successfully controlled blood glucose.", organ: "Coordinated liver, muscle, adipose, and pancreatic responses shape the final post-meal level.", cellular: "The combined effects of insulin signaling, GLUT4 recruitment, glycogen synthesis, and hepatic pathway regulation determine resolution." },
    { id: "fasting-glucagon", order: 11, title: "Fasting and Glucagon", location: "Endocrine pancreas and liver", icon: "↺", movingItem: "Glucagon", mainEvent: "As meal-derived glucose declines, the body shifts toward maintaining circulating fuel.", trigger: "The absorptive phase ends.", next: "The kidney handles the resulting circulating glucose load.", basic: "Lower insulin action and greater glucagon influence support blood glucose between meals.", organ: "Alpha-cell glucagon promotes hepatic glycogenolysis and gluconeogenesis during fasting.", cellular: "Falling insulin-to-glucagon influence reverses fed-state enzyme regulation and increases hepatic glucose production." },
    { id: "kidney-urine", order: 12, title: "Kidney and Urine", location: "Renal tubule and urine", icon: "◫", movingItem: "Glucose", mainEvent: "The kidney filters circulating glucose and attempts to reabsorb it.", trigger: "Blood containing the pathway's final glucose state reaches the renal circulation.", next: "The guided pathway is complete.", basic: "Urinary glucose reflects whether the filtered glucose load exceeds renal reabsorptive capacity.", organ: "The kidney normally reabsorbs filtered glucose; sustained hyperglycemia can produce glycosuria and osmotic water loss.", cellular: "Renal sodium-glucose cotransport is insulin independent but has a finite reabsorptive capacity." }
  ];

  const normalStates = [
    indicators("Normal","Low","Normal","Low","Normal","None","Low"), indicators("Normal","Low","Normal","Low","Normal","None","Low"), indicators("Normal","Low","Normal","Low","Normal","None","Low"),
    indicators("Elevated","Low","Normal","Low","Normal","None","Low"), indicators("Elevated","Elevated","Low","Low","Normal","None","Low"), indicators("Elevated","Elevated","Low","Low","Low","None","Low"),
    indicators("High","High","Low","Low","Low","None","Low"), indicators("High","High","Low","Normal","Low","None","Low"), indicators("Elevated","High","Low","High","Low","None","Low"),
    indicators("Normal","Normal","Low","Normal","Low","None","Low"), indicators("Normal","Low","Normal","Low","Normal","None","Low"), indicators("Normal","Low","Normal","Normal","Normal","None","Low")
  ];
  const type1States = [
    indicators("Normal","Very low","Normal","Low","Normal","None","Low"), indicators("Normal","Very low","Normal","Low","Normal","None","Low"), indicators("Normal","Very low","Normal","Low","Normal","None","Low"),
    indicators("Elevated","Very low","Normal","Low","Normal","None","Low"), indicators("Elevated","Very low","Normal","Low","Normal","None","Low"), indicators("High","Very low","Elevated","Low","Elevated","None","Low"),
    indicators("High","Very low","Elevated","Low","High","None","Elevated"), indicators("High","Very low","Elevated","Low","High","None","Elevated"), indicators("High","Very low","Elevated","Low","High","None","Elevated"),
    indicators("High","Very low","Elevated","Low","High","None","High"), indicators("High","Very low","High","Low","High","None","High"), indicators("High","Very low","High","Low","High","Elevated","High")
  ];
  const type2States = [
    indicators("Normal","Low","Normal","Low","Normal","None","Low"), indicators("Normal","Low","Normal","Low","Normal","None","Low"), indicators("Normal","Low","Normal","Low","Normal","None","Low"),
    indicators("Elevated","Low","Normal","Low","Normal","None","Low"), indicators("Elevated","Elevated","Low","Low","Normal","None","Low"), indicators("Elevated","Elevated","Low","Low","Normal","None","Low"),
    indicators("High","High","Low","Low","Normal","None","Low"), indicators("High","High","Low","Low","Normal","None","Low"), indicators("High","High","Low","Low","Normal","None","Low"),
    indicators("Elevated","Elevated","Low","Low","Normal","None","Low"), indicators("Elevated","Normal","Normal","Low","Elevated","None","Low"), indicators("Elevated","Normal","Normal","Low","Elevated","Low","Low")
  ];

  const normalOverrides = {
    liver: { difference: "In normal physiology, rising insulin shifts the liver toward glucose use and glycogen storage while hepatic glucose output falls.", basic: "The liver begins storing glucose, so its glucose output decreases.", organ: "Insulin promotes hepatic glucose uptake, use, and glycogen synthesis while inhibiting glycogen breakdown and gluconeogenesis.", cellular: "Hepatocytes increase glucokinase and glycogen-synthase activity; insulin opposes glycogenolysis and gluconeogenesis." },
    pancreas: { difference: "Normal beta cells mount a strong insulin response to rising glucose, while glucagon is relatively suppressed.", basic: "Rising glucose triggers a strong insulin release and lowers glucagon influence.", organ: "Pancreatic beta cells release insulin, while alpha-cell glucagon output is relatively suppressed in the fed state.", cellular: "Beta-cell glucose metabolism raises ATP and calcium-dependent exocytosis releases insulin." },
    "insulin-signal": { difference: "The insulin signal is effective, so target tissues begin increasing glucose handling.", basic: "Insulin successfully tells target tissues to take up and store fuel.", organ: "Liver, skeletal muscle, and adipose tissue coordinate a normal fed-state response.", cellular: "Insulin-receptor signaling recruits GLUT4 in skeletal muscle and adipocytes; liver responses use distinct hepatic glucose-handling pathways." },
    "muscle-adipose": { difference: "Normal insulin sensitivity produces high peripheral glucose uptake and promotes glycogen and fat storage.", basic: "Muscle and fat cells respond well to insulin, pulling more glucose from blood.", organ: "Skeletal muscle increases glucose use and glycogen storage; adipose tissue increases glucose use for fat deposition.", cellular: "GLUT4 translocation increases glucose entry in skeletal muscle and adipocytes, while insulin suppresses hormone-sensitive lipase." },
    baseline: { difference: "Effective uptake plus reduced hepatic output allows glucose to return toward normal.", basic: "The meal-related glucose rise resolves because uptake and storage now exceed new glucose entry.", organ: "Coordinated pancreatic, liver, muscle, and adipose responses restore the circulating level.", cellular: "Effective receptor signaling and storage-pathway activation reduce circulating glucose and then reduce insulin secretion." },
    "fasting-glucagon": { difference: "As insulin falls, glucagon restores hepatic glucose output enough to maintain blood glucose between meals.", basic: "Glucagon rises during fasting and tells the liver to release glucose.", organ: "The alpha-cell-to-liver axis increases glycogenolysis and gluconeogenesis as the fed state ends.", cellular: "The lower insulin-to-glucagon influence reverses fed-state enzyme regulation without producing a pathologic ketone state." },
    "kidney-urine": { difference: "The controlled glucose level remains within renal reabsorptive capacity, so urinary glucose is absent.", basic: "The kidneys reabsorb filtered glucose, so essentially none is lost in urine.", organ: "Renal tubules reclaim filtered glucose under this normal modeled load.", cellular: "Sodium-glucose cotransport reabsorbs the filtered load without reaching its transport limit." }
  };

  const type1Overrides = {
    meal: { difference: "Severe insulin deficiency is already present, but it does not prevent the meal from entering the digestive tract." },
    mouth: { difference: "Type 1 diabetes does not prevent oral processing of carbohydrate." }, stomach: { difference: "Gastric processing remains essentially the same at this checkpoint." },
    "small-intestine": { difference: "Intestinal glucose absorption remains intact and does not require insulin.", basic: "Glucose is absorbed normally even though insulin is severely deficient.", organ: "The small intestine still delivers glucose into portal blood.", cellular: "Intestinal sodium-glucose transport is insulin independent, so the meal's glucose still enters the circulation." },
    "portal-blood": { difference: "Glucose reaches portal blood normally, but very little insulin is available to prepare target tissues.", basic: "Blood glucose rises while insulin remains very low.", organ: "Portal delivery is intact; the downstream endocrine response is the problem.", cellular: "Absorption proceeds independently of insulin, so severe insulin deficiency does not blunt the glucose load." },
    liver: { difference: "Without adequate insulin, hepatic glucose storage is impaired and hepatic glucose output is not properly suppressed.", basic: "The liver stores less incoming glucose and continues adding glucose to blood.", organ: "The liver does not shift effectively into fed-state storage, so blood glucose rises further.", cellular: "Low insulin action fails to promote glycogen synthesis or adequately inhibit glycogenolysis and gluconeogenesis." },
    pancreas: { difference: "Beta-cell insulin output is absent or severely deficient, so glucagon's influence is relatively unopposed.", basic: "The pancreas cannot provide the insulin response needed for the meal.", organ: "Damaged beta cells provide very little insulin; alpha-cell glucagon influence becomes relatively excessive.", cellular: "The normal glucose-stimulated insulin secretory pathway cannot produce an adequate output because functional beta-cell mass is severely reduced." },
    "insulin-signal": { difference: "There is too little insulin signal to recruit a normal response in insulin-dependent target tissues.", basic: "The fed-state signal is missing, so insulin-dependent uptake stays low.", organ: "Skeletal muscle and adipose tissue receive inadequate insulin, while hepatic output remains high.", cellular: "Without adequate insulin-receptor activation, GLUT4 recruitment in skeletal muscle and adipocytes remains low; insulin-independent tissues can still take up glucose." },
    "muscle-adipose": { difference: "Insulin-dependent glucose uptake and storage remain low, while loss of insulin's restraint permits fat mobilization.", basic: "Muscle and fat do not increase insulin-dependent glucose uptake normally; fat breakdown begins to rise.", organ: "Skeletal-muscle glycogen storage is impaired and adipose lipolysis increases.", cellular: "Low GLUT4 recruitment limits insulin-dependent uptake, and hormone-sensitive lipase is no longer adequately inhibited." },
    baseline: { difference: "The pathway does not resolve: glucose remains high, hepatic output remains high, and ketone production accumulates.", basic: "Blood glucose stays high because uptake is low and the liver keeps releasing glucose.", organ: "The liver continues glucose production and converts mobilized fatty acids toward ketones.", cellular: "Inadequate insulin action fails to restrain gluconeogenesis, glycogenolysis, lipolysis, and ketogenesis." },
    "fasting-glucagon": { difference: "Fasting intensifies the imbalance because glucagon-driven hepatic output and fat-derived ketone production remain unopposed.", basic: "During fasting, high glucagon influence adds more glucose and ketones instead of stabilizing the pathway.", organ: "The liver increases glycogenolysis, gluconeogenesis, and ketone formation while adipose tissue supplies fatty acids.", cellular: "Very low insulin with high glucagon favors hormone-sensitive lipase activity, hepatic fatty-acid delivery, and ketogenesis." },
    "kidney-urine": { difference: "The sustained high filtered glucose load exceeds renal reabsorptive capacity, so glucose appears in urine.", basic: "Persistently high blood glucose spills into urine; ketones remain high in this untreated model.", organ: "The kidney cannot reabsorb the entire filtered glucose load, producing glycosuria and osmotic water loss.", cellular: "Renal sodium-glucose cotransport reaches its reabsorptive limit; excess filtered glucose remains in tubular fluid." }
  };

  const type2Overrides = {
    meal: { difference: "Insulin resistance is present, but meal entry and early digestion are unchanged." }, mouth: { difference: "Type 2 diabetes does not prevent oral carbohydrate processing." }, stomach: { difference: "Gastric processing remains essentially the same at this checkpoint." },
    "small-intestine": { difference: "Intestinal absorption remains intact; insulin resistance acts mainly in downstream target tissues.", basic: "Glucose absorption is normal, so the same glucose load enters blood.", organ: "The small intestine delivers glucose into portal blood despite insulin resistance.", cellular: "Intestinal sodium-glucose transport is insulin independent and remains active." },
    "portal-blood": { difference: "Blood glucose rises and beta cells begin producing insulin, but resistant tissues will require a stronger signal.", basic: "Glucose and insulin both begin rising, but the insulin signal will be less effective.", organ: "Portal glucose reaches the liver and stimulates pancreatic beta-cell compensation.", cellular: "The glucose load is intact; the later defect is reduced response to insulin-receptor signaling." },
    liver: { difference: "Insulin is present, but hepatic insulin resistance prevents glucose output from being suppressed as effectively as normal.", basic: "The liver does not reduce its glucose output enough, even though insulin is rising.", organ: "The resistant liver stores incoming fuel less effectively and continues more glucose production.", cellular: "Impaired insulin signaling weakens glycogen-synthesis support and suppression of gluconeogenesis." },
    pancreas: { difference: "Beta cells compensate by producing high insulin, but target tissues remain resistant.", basic: "The pancreas releases plenty of insulin, yet blood glucose remains high.", organ: "Beta-cell compensation raises insulin output in response to persistent glucose elevation.", cellular: "Glucose-stimulated secretion remains present in this early modeled Type 2 response; late beta-cell failure is not modeled." },
    "insulin-signal": { difference: "Insulin reaches target tissues, but reduced receptor-pathway effectiveness produces an inadequate response.", basic: "The insulin message is present but target tissues do not respond strongly enough.", organ: "Muscle, adipose tissue, and liver show reduced responsiveness despite elevated insulin.", cellular: "Impaired insulin-receptor signaling reduces GLUT4 recruitment in skeletal muscle and adipocytes." },
    "muscle-adipose": { difference: "Peripheral glucose uptake remains low because insulin resistance limits GLUT4 recruitment and storage responses.", basic: "Muscle and fat cells take up less glucose than expected for the high insulin level.", organ: "Skeletal muscle clears less glucose and adipose storage responses are less effective.", cellular: "Reduced insulin signaling produces less GLUT4 at the membrane, so uptake is lower than in Normal physiology." },
    baseline: { difference: "Blood glucose declines only partially because tissue uptake is reduced and hepatic output was not fully suppressed.", basic: "Blood glucose stays elevated longer even though insulin is present.", organ: "Compensatory insulin cannot fully overcome resistance in liver, skeletal muscle, and adipose tissue.", cellular: "Persistent signaling resistance limits GLUT4 recruitment and hepatic pathway suppression." },
    "fasting-glucagon": { difference: "Between meals, hepatic output rises from an already incompletely suppressed state, prolonging hyperglycemia.", basic: "The liver adds glucose during fasting while insulin sensitivity remains reduced.", organ: "Glucagon supports hepatic output, and resistant hepatic insulin signaling provides less restraint.", cellular: "Glycogenolysis and gluconeogenesis rise as insulin influence falls; ketones remain low in this modeled early Type 2 state." },
    "kidney-urine": { difference: "The modeled persistent elevation produces a low amount of urinary glucose, while ketones remain low.", basic: "Some glucose appears in urine because blood glucose stayed elevated; this does not mimic the Type 1 ketone pattern.", organ: "The kidney reabsorbs most filtered glucose, but the sustained load produces limited glycosuria in this model.", cellular: "Filtered glucose begins to exceed renal reabsorptive capacity, while retained insulin restrains the marked ketogenesis seen in Type 1." }
  };

  const makeSteps = (states, overrides) => shared.map((step, index) => ({
    ...step, ...overrides[step.id], physiology: states[index],
    sourceIds: ["PHYS2-E4-BP-005", "CORE_PHYS2-E4-Pancreas-v1.2"], conceptIds: [], relatedQuestionIds: []
  }));

  window.GlucoseILGData = {
    conditionData: {
      normal: { label: "Normal", summary: "A coordinated insulin response promotes fuel uptake and storage, then glucagon supports the later fasting transition.", steps: makeSteps(normalStates, normalOverrides) },
      type1: { label: "Type 1 Diabetes", summary: "Severe insulin deficiency prevents a normal fed-state response, so hyperglycemia, hepatic output, fat mobilization, ketones, and glycosuria accumulate.", steps: makeSteps(type1States, type1Overrides) },
      type2: { label: "Type 2 Diabetes", summary: "Insulin is present and elevated early, but resistant liver, skeletal muscle, and adipose tissue respond inadequately, prolonging hyperglycemia.", steps: makeSteps(type2States, type2Overrides) }
    },
    particles: [{ id: "active-particle", type: "meal", label: "Meal", startStep: "meal", destinationStep: "mouth", speed: 1, visible: true }],
    sourceNotes: {
      primary: ["FINAL WI 26 Week 11 - Endocrine Pancreas.pdf", "Week 11 Lecture Manual - Endocrine Pancreas.pdf", "Lab 12 - Calcium Regulation and Diabetes.pdf", "PHYS2-E4-BP-005_Endocrine_Pancreas", "CORE_PHYS2-E4-Pancreas_v1.2", "Mapping_Store_PHYS2-E4-Pancreas_v2.2"],
      inferredTeachingBridges: ["Qualitative step timing and the exact points at which Type 1 ketones and Type 2 low glycosuria appear are teaching-sequence bridges, not diagnostic thresholds."]
    }
  };
})();
